"""Plumbing for Lab 2.2 (travel disruption tool loop). Taken from the same harness as Demo 2C. You do not edit this file.

Flight XA482 was cancelled. For traveler T-1001 the assistant reads (flight status, alternatives, hotels, loyalty tier) and then writes
(rebook, book a hotel, notify). Each stage changes how the HARNESS runs the tool calls of one assistant turn, using the pieces you write in lab.py:

  stage 1  one tool call after the other; no loyalty tool; a timed-out write is just an error string
  stage 2  + your loyalty tool and your concurrent executor: the reads overlap
  stage 3  + your write gate: dependent writes run in order, and only on references a tool really returned (a recorded batch is replayed)
  stage 4  + your idempotency key and structured timeout result: a retried write is replayed, not repeated (a recorded retry is replayed)
  stage 5  + your iteration guard: a model that never stops is cut off, and the whole run is judged
"""
import hashlib  # noqa: F401  (used by the solution in lab.py)
import json
import pathlib

from claude_client import ask, text_of, tool_calls_of
from travel_services import PREREQ, READ_TOOLS, ServiceTimeout, TravelServices, analyse, load_scenario

HERE = pathlib.Path(__file__).parent
EVIDENCE = HERE / "evidence"
DEPENDS_ON = dict(PREREQ)
HOOKS = {"loyalty_tool": None, "run_concurrently": None, "gate": None, "key_for": None, "timeout_result": None, "run_agent": None}
STAGE_TITLES = {1: "one by one, no loyalty tool", 2: "concurrent reads + loyalty tool", 3: "dependent writes gated",
                4: "idempotent writes", 5: "iteration guard, final run"}


def configure(**pieces):
    HOOKS.update(pieces)


# ---------------------------------------------------------------- tools and prompts (given)
def _object(properties, required):
    return {"type": "object", "properties": properties, "required": required, "additionalProperties": False}


TEXT = {"type": "string"}
BASE_TOOLS = [
    {"name": "flight_status", "description": "Read-only. Current status and reason for one flight number. Use first to confirm the cancellation. Does not change anything.",
     "input_schema": _object({"flight_no": TEXT}, ["flight_no"])},
    {"name": "rebooking_options", "description": "Read-only. Alternative flights (with seats left and change fee) for a PNR whose flight was cancelled. Does not rebook.",
     "input_schema": _object({"pnr": TEXT}, ["pnr"])},
    {"name": "hotel_availability", "description": "Read-only. Hotels near an airport for a date with rate, rooms left and shuttle. Does not book.",
     "input_schema": _object({"airport": TEXT, "date": TEXT}, ["airport", "date"])},
    {"name": "rebook_flight", "description": "WRITE. Rebook the PNR onto a chosen option_id. Returns a confirmation ref (RB-...). Needed before any hotel or notification. May time out; the outcome is then unknown.",
     "input_schema": _object({"pnr": TEXT, "option_id": TEXT}, ["pnr", "option_id"])},
    {"name": "book_hotel", "description": "WRITE. Book one hotel for the stranded traveler. Requires the confirmed rebook_ref returned by rebook_flight; never guess it.",
     "input_schema": _object({"hotel_id": TEXT, "rebook_ref": TEXT, "nights": {"type": "integer"}, "guest": TEXT}, ["hotel_id", "rebook_ref", "nights", "guest"])},
    {"name": "notify_traveler", "description": "WRITE. Send the traveler the final itinerary. Requires both the rebook_ref and the hotel_ref returned by the earlier writes.",
     "input_schema": _object({"traveler_id": TEXT, "rebook_ref": TEXT, "hotel_ref": TEXT, "channel": TEXT}, ["traveler_id", "rebook_ref", "hotel_ref"])},
]

SYSTEM = """You are the disruption desk assistant for an airline. A flight was cancelled; rebook the traveler,
book a hotel within their tier's hotel rate cap, and notify them. Check status, alternatives, hotels and loyalty
tier first (they are independent - request them together). Writes depend on each other: the hotel needs the
confirmed rebooking reference, the notification needs both references. Use only references that tool results
returned. If a tool result says the outcome is unknown, retry with IDENTICAL arguments. Finish with one short summary."""


def tools_for(stage):
    tools = list(BASE_TOOLS)
    if stage >= 2:
        if HOOKS["loyalty_tool"] is None:
            raise NotImplementedError("TODO 1: write the loyalty_tier tool definition")
        tools.insert(3, HOOKS["loyalty_tool"])
    return tools


def request_text(scenario):
    traveler = scenario["travelers"]["T-1001"]
    return (f"Flight {scenario['flight']['flight_no']} ({scenario['flight']['route']}) is cancelled. Traveler T-1001 {traveler['name']}, "
            f"PNR {traveler['pnr']}. Rebook them, book a hotel at LHR for 2026-10-03 (1 night), and notify them.")


class RunState:
    """Facts about this conversation. `succeeded`: tool names that returned OK. `refs`: references the tools returned."""

    def __init__(self):
        self.succeeded = set()
        self.refs = set()


# ---------------------------------------------------------------- running the tool calls of ONE assistant turn
def tool_result(call, content, is_error=False):
    block = {"type": "tool_result", "tool_use_id": call.id, "content": content if isinstance(content, str) else json.dumps(content)}
    if is_error:
        block["is_error"] = True
    return block


def call_one(services, call, state, stage):
    """Run one tool call and wrap the outcome. From stage 4 a write carries your idempotency key and a timeout is structured."""
    args = dict(call.input)
    key = HOOKS["key_for"](call.name, args) if stage >= 4 and call.name not in READ_TOOLS else None
    try:
        output = services.call(call.name, args, idempotency_key=key) if key else services.call(call.name, args)
        state.succeeded.add(call.name)
        if isinstance(output, dict) and output.get("ref"):
            state.refs.add(output["ref"])
        return tool_result(call, output)
    except ServiceTimeout as error:
        if stage >= 4:
            return tool_result(call, HOOKS["timeout_result"](call.name, error), True)
        return tool_result(call, f"Error: {error}", True)
    except Exception as error:  # noqa: BLE001 - a tool failure becomes an is_error result
        return tool_result(call, {"error": type(error).__name__, "retryable": False, "message": str(error)}, True)


def run_tools(services, calls, state, stage):
    """Return ONE tool_result block per tool_use, in the order the tool_use blocks were requested."""
    run_one = lambda call: call_one(services, call, state, stage)  # noqa: E731
    if stage <= 1:
        return [run_one(c) for c in calls]
    if stage == 2:  # everything at once: the demo's stage-2 executor
        return HOOKS["run_concurrently"](run_one, calls)
    by_id = {}
    reads = [c for c in calls if c.name in READ_TOOLS]
    for call, block in zip(reads, HOOKS["run_concurrently"](run_one, reads)):
        by_id[call.id] = block
    for call in calls:  # the writes, one at a time, in the order requested
        if call.name in READ_TOOLS:
            continue
        problem = HOOKS["gate"](call.name, dict(call.input), state)
        by_id[call.id] = tool_result(call, problem, True) if problem else run_one(call)
    return [by_id[c.id] for c in calls]


def take_turn(create, services, state, messages, log, stage, turn):
    """One model call and, if the model asked for tools, one user message holding ALL the results. Returns the final dict, or None to continue."""
    response = create(messages, system=SYSTEM, tools=tools_for(stage), max_tokens=1024)
    calls = tool_calls_of(response)
    log["trace"].append({"turn": turn, "stop_reason": response.stop_reason, "tools": [c.name for c in calls]})
    if response.stop_reason != "tool_use" or not calls:
        return {"turns": turn, "stopped": "end_turn", "final_text": text_of(response), **log}
    messages.append({"role": "assistant", "content": [b.model_dump(exclude_none=True) for b in response.content]})
    results = run_tools(services, calls, state, stage)
    names = {c.id: c.name for c in calls}
    for block in results:
        log["tool_results"].append({"turn": turn, "tool": names[block["tool_use_id"]], "is_error": bool(block.get("is_error")), "content": block["content"][:240]})
    messages.append({"role": "user", "content": results})
    return None


def new_log():
    return {"trace": [], "tool_results": []}


# ---------------------------------------------------------------- recorded models for the replays (no API key, no randomness)
class _Text:
    type = "text"

    def __init__(self, text):
        self.text = text

    def model_dump(self, exclude_none=True):
        return {"type": "text", "text": self.text}


class _Use:
    type = "tool_use"

    def __init__(self, i, name, args):
        self.id, self.name, self.input = i, name, args

    def model_dump(self, exclude_none=True):
        return {"type": "tool_use", "id": self.id, "name": self.name, "input": self.input}


class _Resp:
    def __init__(self, content, stop):
        self.content, self.stop_reason = content, stop


class RecordedBatch:
    """The model asks for the three dependent writes in ONE turn, with a reference it made up."""

    def create(self, messages, **_):
        if len(messages) > 1:
            return _Resp([_Text("Done.")], "end_turn")
        return _Resp([_Use("rec_1", "rebook_flight", {"pnr": "K7QD2L", "option_id": "OPT-B"}),
                      _Use("rec_2", "book_hotel", {"hotel_id": "HTL-PARKSIDE", "rebook_ref": "RB-0001", "nights": 1, "guest": "Mira Okafor"}),
                      _Use("rec_3", "notify_traveler", {"traveler_id": "T-1001", "rebook_ref": "RB-0001", "hotel_ref": "HB-0001"})], "tool_use")


class RecordedRetry:
    """The model rebooks, sees an error, and retries with IDENTICAL arguments, as the system prompt tells it to."""

    def create(self, messages, **_):
        turn = sum(1 for m in messages if m["role"] == "assistant")
        if turn < 2:
            return _Resp([_Use(f"rec_{turn}", "rebook_flight", {"pnr": "K7QD2L", "option_id": "OPT-B"})], "tool_use")
        return _Resp([_Text("Rebooked.")], "end_turn")


class RecordedRunaway:
    """A model that never stops asking for the flight status. After 40 turns it raises, so that a loop without a guard still ends."""

    def create(self, messages, **_):
        turn = sum(1 for m in messages if m["role"] == "assistant")
        if turn >= 40:
            raise RuntimeError("the model asked for a tool 40 times in a row and the loop never stopped it")
        return _Resp([_Use(f"rec_{turn}", "flight_status", {"flight_no": "XA482"})], "tool_use")


# ---------------------------------------------------------------- reporting
def hr(title):
    print(f"\n{'=' * 8} {title} {'=' * 8}")


def save(name, payload):
    EVIDENCE.mkdir(exist_ok=True)
    (EVIDENCE / name).write_text(json.dumps(payload, indent=1, default=str), encoding="utf-8")


def scenario_and_services(latency_scale=1.0):
    scenario = load_scenario(HERE / "data" / "scenario.json")
    return scenario, TravelServices(scenario, latency_scale=latency_scale)


def measure(services, result):
    a = analyse(services.events, services.ledger())
    return {"turns": result["turns"], "stopped": result["stopped"], "read_span_s": a["read_phase_span_s"], "rebookings": a["rebookings"],
            "hotels": a["hotel_bookings"], "notifications": a["notifications"], "unverified": a["unverified_entries"],
            "order_violations": a["order_violations"], "writes_overlap": a["writes_overlap"], "replays": a["replays"]}


def line(label, m):
    span = "-" if m["read_span_s"] is None else f"{m['read_span_s']:.2f}"
    print(f"  {label:<34} turns {m['turns']:>2}  read phase {span:>5}s  rebookings {m['rebookings']}  hotels {m['hotels']}  "
          f"notices {m['notifications']}  unverified {m['unverified']}  order violations {len(m['order_violations'])}  replays {m['replays']}")


def history(upto):
    print("\nPROGRESS ACROSS STAGES (live run of the whole disruption)")
    print(f"{'stage':<7}{'what changed':<34}{'read s':>7}{'rebook':>8}{'hotels':>8}{'unverif':>9}{'order bad':>10}{'turns':>7}")
    for s in range(1, upto + 1):
        path = EVIDENCE / f"stage{s}.json"
        if not path.exists():
            print(f"{s:<7}{STAGE_TITLES[s]:<34}{'(run this stage first)':>30}")
            continue
        m = json.loads(path.read_text(encoding="utf-8"))["live"]
        span = "-" if m["read_span_s"] is None else f"{m['read_span_s']:.2f}"
        print(f"{s:<7}{STAGE_TITLES[s]:<34}{span:>7}{m['rebookings']:>8}{m['hotels']:>8}{m['unverified']:>9}{len(m['order_violations']):>10}{m['turns']:>7}")


def replay(model, stage, max_turns=10):
    scenario, services = scenario_and_services(latency_scale=0.3)
    try:
        result = HOOKS["run_agent"](model.create, services, request_text(scenario), stage, max_turns)
    except RuntimeError as exc:
        return {"crashed": str(exc)}, services
    return measure(services, result), services


def live(stage):
    scenario, services = scenario_and_services()
    result = HOOKS["run_agent"](ask, services, request_text(scenario), stage)
    return measure(services, result), result, services


def run_stage(stage):
    hr(f"STAGE {stage} - {STAGE_TITLES[stage]}")
    out = {"stage": stage}
    if stage == 3:
        print("recorded batch: rebook_flight, book_hotel and notify_traveler in ONE turn, with a made-up reference (RB-0001)")
        stage2_run, _ = replay(RecordedBatch(), 2)
        line("replay through the stage-2 executor", stage2_run)
        stage3_run, _ = replay(RecordedBatch(), 3)
        line("replay through your write gate", stage3_run)
        out["replay_before"], out["replay_after"] = stage2_run, stage3_run
    if stage == 4:
        print("recorded retry: rebook_flight times out (the booking is committed, the acknowledgement is lost), and the model retries with the same arguments")
        before, _ = replay(RecordedRetry(), 3)
        after, _ = replay(RecordedRetry(), 4)
        line("replay without a key (stage 3)", before)
        line("replay with your key (stage 4)", after)
        out["replay_before"], out["replay_after"] = before, after
    if stage == 5:
        crashed = replay(RecordedRunaway(), 4, max_turns=8)[0]
        print(f"a model that never stops, with your guard (max_turns 8): {crashed if 'crashed' in crashed else 'stopped=' + crashed['stopped'] + ' after ' + str(crashed['turns']) + ' turns'}")
        out["runaway"] = crashed
    print("\nlive run with Claude:")
    measured, result, services = live(stage)
    line(f"stage {stage}", measured)
    for step in result["trace"]:
        print(f"    turn {step['turn']}: stop_reason={step['stop_reason']:<9} tools={step['tools']}")
    errors = [r for r in result["tool_results"] if r["is_error"]]
    for r in errors[:3]:
        print(f"    the model saw an error from {r['tool']}: {r['content'][:150]}")
    print(f"  final answer: {result['final_text'][:300]}")
    out["live"], out["final_text"], out["errors_seen"] = measured, result["final_text"], errors[:3]
    save(f"stage{stage}.json", out)
    history(stage)
    if stage == 5:
        ok = (measured["rebookings"] == 1 and measured["unverified"] == 0 and not measured["order_violations"] and not measured["writes_overlap"]
              and "crashed" not in out["runaway"] and out["runaway"]["stopped"] == "max_turns")
        print("\nGATE: one rebooking, nothing unverified, writes in order, the runaway stopped -> " + ("PASS" if ok else "FAIL"))
