"""Plumbing for Lab 3.1. Copied from Demo 3A. You do not edit this file.

It loads the demo's data and holds the policy rule engine, so lab.py shows only your work.
"""
import json
from pathlib import Path

DATA = Path(__file__).parent / "data"


def load(name):
    return json.loads((DATA / name).read_text(encoding="utf-8"))


BRIEFS = load("briefs.json")
CLAIMS = load("expense_reports.json")
POLICY = load("policy.json")
HISTORY = load("employee_history.json")
EXTRACTION_SCHEMA = load("extraction_schema.json")

ANSWER_FORMAT = 'Reply with JSON only: {"decision": "approve" | "reject" | "escalate", "reasons": [short strings]}.'


def policy_text():
    return "\n".join(f"{name.upper()}: {body}" for name, body in POLICY["text"].items())


def claim_facts(claim):
    return (f"Claim {claim['id']} from employee {claim['employee_id']}. Attachments: {len(claim['attachments'])}. "
            f"Pre-approval id: {claim['preapproval_id'] or 'none'}.\nClaim text: {claim['text']}")


def text_of(response):
    return "".join(block.text for block in response.content if block.type == "text")


def json_in(text):
    """Pull the first JSON object out of a reply (models sometimes add a sentence or code fences)."""
    start, end = text.find("{"), text.rfind("}")
    try:
        return json.loads(text[start:end + 1]) if start != -1 and end > start else None
    except json.JSONDecodeError:
        return None


def decision_in(text):
    data = json_in(text)
    return data["decision"] if isinstance(data, dict) and data.get("decision") in ("approve", "reject", "escalate") else "invalid"


def to_usd(amount, currency):
    return amount * POLICY["fx_to_usd"][currency]


def apply_policy(fields, claim):
    """Deterministic review. Hard violation -> reject; else soft violation -> escalate; else approve. Returns (decision, codes)."""
    hard, soft = [], []
    usd = to_usd(fields["amount"], fields["currency"])
    category, rules = fields["category"], POLICY["categories"][fields["category"]]

    past = HISTORY["history"].get(claim["employee_id"], [])
    if any(h["merchant"].lower() == fields["merchant"].lower() and h["date"] == fields["date"]
           and abs(h["amount_usd"] - usd) < 0.01 for h in past):
        hard.append("duplicate_submission")
    if usd > POLICY["receipt_required_over_usd"] and not claim["attachments"]:
        hard.append("missing_receipt")
    if category == "airfare" and fields["cabin"] not in rules["allowed_cabins"]:
        hard.append("cabin_not_economy")
    if category == "software":
        approval = HISTORY["preapprovals"].get(claim["preapproval_id"])
        if not (approval and approval["category"] == "software" and approval["max_usd"] >= usd):
            hard.append("missing_preapproval")

    if usd > POLICY["manager_approval_over_usd"]:
        soft.append("manager_approval_required")
    if category == "meals":
        if usd / max(fields["attendees"] or 1, 1) > rules["per_person_cap_usd"]:
            soft.append("meals_over_cap")
        if (fields["alcohol_amount"] or 0) > 0:
            soft.append("alcohol_present")
    if category == "lodging" and usd / max(fields["nights"] or 1, 1) > rules["per_night_cap_usd"]:
        soft.append("lodging_over_cap")
    if category == "ground_transport" and usd > rules["cap_usd"]:
        soft.append("ground_transport_over_cap")
    if category == "client_gift":
        soft.append("client_gift_compliance_review")
        if usd > rules["cap_usd"]:
            soft.append("client_gift_over_cap")

    if hard:
        return "reject", hard + soft
    return ("escalate", soft) if soft else ("approve", [])
