"""Plumbing for Demo 1D and Lab 1D (cost engineering). In the lab you do not edit this file.

The story: an accounts-payable team checks supplier invoices against a ~6,000-token procurement policy. The policy is the
same on every request, so it dominates the bill. Four stages cut the cost, and each one has a silent way to fail:
  1  meter it            a usage ledger and a monthly projection
  2  count before send   count_tokens and a budget gate
  3  cache the prefix    prompt caching, the silent invalidator, the fix
  4  batch it            Message Batches, the join on custom_id, a four-way cost table
Five pieces are supplied from outside through configure(): ask_checker, system_blocks, count_request_tokens,
batch_requests and join_by_custom_id.
"""
import datetime
import json
import math
import pathlib
import random
import re
import time
import uuid
from dataclasses import dataclass

from claude_client import MODEL_BALANCED, MODEL_FAST, PRICE_PER_MTOK, get_client, text_of

HERE = pathlib.Path(__file__).parent
DATA = HERE / "data"
EVIDENCE = HERE / "evidence"
HOOKS = {}  # filled by demo.py / lab.py
CALLS = []
MONTHLY = 100_000
MAX_TOKENS = 600
CACHE_FLOOR = {}  # tokens: below the floor a prefix is silently NOT cached. 512 for Sonnet 5.5 and Haiku 5.5 (the default below); Haiku 4.5 needed 4096
WRITE_MULT = {"5m": 1.25, "1h": 2.0}
READ_MULT = 0.10
BATCH_MULT = 0.50
POLL_SECONDS = 15
MAX_POLLS = 40

INSTRUCTIONS = (
    "You are the invoice policy-compliance checker for Group Accounts Payable.\n"
    "Read the procurement policy below and decide whether the invoice in the user message is compliant.\n"
    "Apply ONLY the verifiable clauses (identifiers of the form P-x.y). Respond with a single JSON object and nothing else:\n"
    '{"invoice_id": string, "compliant": boolean, "violated_clauses": [string], "rationale": string}\n'
    "violated_clauses lists every violated clause id in ascending order (empty when compliant). "
    "rationale is one or two sentences that cite the facts used.\n"
    "=== PROCUREMENT POLICY (authoritative) ===\n"
)
VERDICT_SCHEMA = {
    "type": "object",
    "properties": {"invoice_id": {"type": "string"}, "compliant": {"type": "boolean"},
                   "violated_clauses": {"type": "array", "items": {"type": "string"}}, "rationale": {"type": "string"}},
    "required": ["invoice_id", "compliant", "violated_clauses", "rationale"],
    "additionalProperties": False,
}
VERDICT_FORMAT = {"type": "json_schema", "schema": VERDICT_SCHEMA}


def configure(**hooks):
    HOOKS.update(hooks)


# ================================================================ data
def load_policy(kind="full"):
    return (DATA / {"full": "procurement_policy.txt", "lite": "procurement_policy_lite.txt"}[kind]).read_text(encoding="utf-8")


def load_invoices():
    return [json.loads(line) for line in (DATA / "invoices.jsonl").read_text(encoding="utf-8").splitlines() if line.strip()]


def load_truth():
    return json.loads((DATA / "ground_truth.json").read_text(encoding="utf-8"))


def lab_invoices(invoices):
    """Every third invoice: 10 of the demo's 30."""
    return invoices[::3]


def render_invoice(inv):
    lines = [f"INVOICE {inv['invoice_id']}", f"Vendor: {inv['vendor_name']} (vendor_id {inv['vendor_id']})",
             f"invoice_date: {inv['invoice_date']}   received_date: {inv['received_date']}", f"po_number: {inv['po_number'] or 'NONE'}",
             f"currency: {inv['currency']}   treasury_preapproval: {str(inv['treasury_preapproval']).lower()}",
             f"terms_days: {inv['terms_days']}   early_pay_discount_pct: {inv['early_pay_discount_pct']}", f"category: {inv['category']}",
             f"tax_id: {inv['tax_id'] or 'MISSING'}", "approvals: " + "; ".join(f"{a['name']} ({a['role']})" for a in inv["approvals"]),
             "line items:"]
    for i, ln in enumerate(inv["lines"], 1):
        lines.append(f"  {i}. {ln['description']}  qty {ln['qty']} x {ln['unit_price']} = {ln['line_total']}")
    lines.append(f"total: {inv['total']} {inv['currency']}   total_usd: {inv['total_usd']}")
    if inv.get("notes"):
        lines.append("scan_notes: " + inv["notes"])
    return "\n".join(lines)


def oversized_invoice(base):
    """A 60-page OCR dump attached to an invoice: the case the token gate must stop."""
    rng = random.Random(77)
    words = ["ITEM", "QTY", "UNIT", "TOTAL", "REF", "BATCH", "LOT", "DELIVERED", "SIGNED", "STAMP", "0048", "7731", "GBP", "SUBTOTAL"]
    pages = [f"REMITTANCE ADVICE / SCANNED PAGE {p} OF 60 | " + " ".join(rng.choice(words) for _ in range(70)) for p in range(1, 61)]
    return {**base, "invoice_id": "INV-2026-9999", "notes": " || ".join(pages)}


# ================================================================ requests
def new_salt():
    """A fresh tag per section, so a cache entry from an earlier section cannot hide the first write of the next one."""
    return uuid.uuid4().hex[:8]


def system_text(policy, salt):
    return f"Policy edition: {salt}\n" + INSTRUCTIONS + policy


def stamp():
    """The well-meaning 'audit stamp' that someone adds to the TOP of the prompt: different bytes on every request."""
    return f"[audit] request_id={uuid.uuid4()} processed_at={datetime.datetime.now(datetime.timezone.utc).isoformat(timespec='seconds')}\n"


def build_request(model, policy, inv, salt, cache=False, ttl=None, stamp_in=None):
    """stamp_in: None (no stamp), "system" (the failure) or "user" (the fix)."""
    text = system_text(policy, salt)
    user = "Check this invoice against the policy.\n\n" + render_invoice(inv)
    if stamp_in == "system":
        text = stamp() + text
    elif stamp_in == "user":
        user = stamp().strip() + "\n" + user
    return {"model": model, "max_tokens": MAX_TOKENS, "system": HOOKS["system_blocks"](text, cache, ttl),
            "messages": [{"role": "user", "content": user}], "output_config": {"format": VERDICT_FORMAT}}


def tokens_estimate(text):
    return len(text) // 4


# ================================================================ money: what one call cost
def request_cost(model, usage, batch=False, ttl="5m"):
    price_in, price_out = PRICE_PER_MTOK.get(model, (0.0, 0.0))
    write = getattr(usage, "cache_creation_input_tokens", 0) or 0
    read = getattr(usage, "cache_read_input_tokens", 0) or 0
    cost = ((usage.input_tokens or 0) * price_in + write * price_in * WRITE_MULT[ttl] + read * price_in * READ_MULT
            + (usage.output_tokens or 0) * price_out) / 1_000_000
    return cost * (BATCH_MULT if batch else 1.0)


@dataclass
class Row:
    invoice_id: str
    uncached: int
    cache_write: int
    cache_read: int
    output: int
    cost: float
    verdict: dict | None
    stop_reason: str | None = None

    @property
    def total_in(self):
        return self.uncached + self.cache_write + self.cache_read


def parse_verdict(text):
    try:
        verdict = json.loads(re.sub(r"^```(?:json)?\s*|\s*```$", "", text.strip()))
    except ValueError:
        return None
    ok = isinstance(verdict, dict) and all(k in verdict for k in VERDICT_SCHEMA["required"]) and isinstance(verdict["violated_clauses"], list)
    return verdict if ok else None


def row_from(response, invoice_id, batch=False, ttl="5m"):
    usage = response.usage
    return Row(invoice_id, usage.input_tokens or 0, getattr(usage, "cache_creation_input_tokens", 0) or 0,
               getattr(usage, "cache_read_input_tokens", 0) or 0, usage.output_tokens or 0,
               request_cost(response.model, usage, batch, ttl), parse_verdict(text_of(response)), response.stop_reason)


def send(request, invoice_id, label="", ttl="5m"):
    """One real-time call (the Claude call itself is your TODO 1)."""
    response = HOOKS["ask_checker"](request)
    row = row_from(response, invoice_id, ttl=ttl)
    CALLS.append({"label": label, "model": request["model"], "cost": row.cost})
    return row


def run_sequence(model, policy, invoices, salt, label, **options):
    ttl = options.get("ttl") or "5m"
    return [send(build_request(model, policy, inv, salt, **options), inv["invoice_id"], f"{label}:{inv['invoice_id']}", ttl) for inv in invoices]


def totals(rows):
    return {"requests": len(rows), "uncached": sum(r.uncached for r in rows), "cache_write": sum(r.cache_write for r in rows),
            "cache_read": sum(r.cache_read for r in rows), "output": sum(r.output for r in rows), "cost": sum(r.cost for r in rows),
            "total_in": sum(r.total_in for r in rows)}


def accuracy(rows, truth):
    ok = sum(1 for r in rows if r.verdict and r.verdict["compliant"] == truth[r.invoice_id]["compliant"]
             and sorted(r.verdict["violated_clauses"]) == truth[r.invoice_id]["violated_clauses"])
    return ok, len(rows)


def print_rows(rows, limit=None):
    print(f"{'invoice':<15}{'uncached':>9}{'c.write':>9}{'c.read':>9}{'out':>6}{'cost':>11}")
    for r in rows if limit is None else rows[:limit]:
        print(f"{r.invoice_id:<15}{r.uncached:>9}{r.cache_write:>9}{r.cache_read:>9}{r.output:>6}{'$' + format(r.cost, '.5f'):>11}")
    if limit is not None and len(rows) > limit:
        print(f"... ({len(rows) - limit} more rows)")


def print_ledger():
    total = sum(c["cost"] for c in CALLS)
    print(f"\n[ledger] {len(CALLS)} real-time Claude calls; estimated cost ${total:.4f} (batch cost is counted in its own table)")


def hr(title):
    print(f"\n{'=' * 8} {title} {'=' * 8}")


def save(name, payload):
    EVIDENCE.mkdir(exist_ok=True)
    (EVIDENCE / name).write_text(json.dumps(payload, indent=1, default=str), encoding="utf-8")


# ================================================================ economics (pure functions: normal / cached / batch / batch+cache)
def family(model):
    return "haiku" if "haiku" in model else "sonnet"


def cache_effective(model, prefix_tokens):
    return prefix_tokens >= CACHE_FLOOR.get(family(model), 512)


def expected_hit_rate(ttl, mean_gap_s):
    """Poisson-arrival approximation: a request misses when the previous one is older than the cache lifetime."""
    return 1.0 if mean_gap_s <= 0 else 1.0 - math.exp(-{"5m": 300.0, "1h": 3600.0}[ttl] / mean_gap_s)


def breakeven_hit_rate(ttl):
    """The hit rate above which caching beats not caching: h * read + (1 - h) * write = 1."""
    return (WRITE_MULT[ttl] - 1.0) / (WRITE_MULT[ttl] - READ_MULT)


def per_request_cost(model, prefix, variable, output, cached, batch, hit_rate=0.0, ttl="5m"):
    price_in, price_out = (p / 1e6 for p in PRICE_PER_MTOK[model])
    if cached and cache_effective(model, prefix):
        prefix_cost = prefix * price_in * (hit_rate * READ_MULT + (1 - hit_rate) * WRITE_MULT[ttl])
    else:
        prefix_cost = prefix * price_in
    cost = prefix_cost + variable * price_in + output * price_out
    return cost * (BATCH_MULT if batch else 1.0)


def projection(models, prefix, variable, output, batch_hit_rate=0.5):
    """$ per month at MONTHLY invoices for each model and strategy. Hit rates are INPUTS, not measurements."""
    rows = []
    gap = 3600.0 * 730.0 / MONTHLY
    for alias, model in models.items():
        h5, h1 = expected_hit_rate("5m", gap), expected_hit_rate("1h", gap)
        spec = {"normal": (False, False, 0.0, "5m"), "cached": (True, False, h5, "5m"),
                "batch": (False, True, 0.0, "5m"), "batch+cache": (True, True, batch_hit_rate, "1h")}
        base = per_request_cost(model, prefix, variable, output, False, False)
        for strategy, (cached, batch, hit, ttl) in spec.items():
            cost = per_request_cost(model, prefix, variable, output, cached, batch, hit, ttl)
            note = "BELOW CACHE FLOOR - no saving" if cached and not cache_effective(model, prefix) else ""
            if strategy == "batch+cache" and not note:
                note = f"assumed hit rate {batch_hit_rate:.0%}, 1h TTL; pays only above {breakeven_hit_rate('1h'):.0%}"
            rows.append({"alias": alias, "model": model, "strategy": strategy, "per_request": cost, "monthly": cost * MONTHLY,
                         "saving_pct": 100 * (1 - cost / base), "note": note})
    return rows


def print_projection(rows, title):
    print(title)
    print(f"{'model':<10}{'strategy':<13}{'$/request':>11}{'$/month':>11}{'saving':>9}  note")
    for r in rows:
        print(f"{r['alias']:<10}{r['strategy']:<13}{r['per_request']:>11.5f}{r['monthly']:>11,.0f}{r['saving_pct']:>8.1f}%  {r['note']}")


# ================================================================ prefix diff: why two requests do not share a cache entry
SUSPECTS = {
    "uuid": re.compile(r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}", re.I),
    "iso-timestamp": re.compile(r"\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}"),
    "request id": re.compile(r"(?:request|session|trace)[_-]?id\s*[=:]\s*\S+", re.I),
}


def prefix_text(request):
    """The text the cache keys on: all system blocks up to the last one marked with cache_control."""
    blocks = request["system"] if isinstance(request["system"], list) else [{"text": request["system"]}]
    marked = [i for i, b in enumerate(blocks) if b.get("cache_control")]
    last = marked[-1] if marked else len(blocks) - 1
    return "".join(b["text"] for b in blocks[: last + 1])


def diff_prefixes(a, b):
    """-> (identical, report). The first differing line is the silent invalidator."""
    ta, tb = prefix_text(a), prefix_text(b)
    if ta == tb:
        return True, f"prefix IDENTICAL ({len(ta):,} chars): a second request can read this cache entry."
    i = next((k for k, (x, y) in enumerate(zip(ta, tb)) if x != y), min(len(ta), len(tb)))

    def line(t):
        start, end = t.rfind("\n", 0, i) + 1, t.find("\n", i)
        return t[start:(len(t) if end == -1 else end)][:120]

    left, right = line(ta), line(tb)
    found = [name for name, rx in SUSPECTS.items() if rx.search(left) and rx.search(right) and rx.search(left).group(0) != rx.search(right).group(0)]
    return False, (f"prefix DIFFERS at char {i} of {len(ta):,}\n    request A: {left!r}\n    request B: {right!r}\n"
                   f"  likely volatile content: {', '.join(found) or 'inspect manually'}\n"
                   f"  consequence: only the first {i} chars could ever match, so no later breakpoint can read.")


# ================================================================ batch plumbing
def submit_and_wait(requests, log=print):
    """Submit a batch and poll until it ends. Returns (batch_id, ended). Batches can take up to 24 hours."""
    client = get_client()
    batch = client.messages.batches.create(requests=requests)
    log(f"submitted {len(requests)} requests as {batch.id}")
    for number in range(1, MAX_POLLS + 1):
        batch = client.messages.batches.retrieve(batch.id)
        log(f"  poll {number}: status={batch.processing_status} processing={batch.request_counts.processing} succeeded={batch.request_counts.succeeded}")
        if batch.processing_status == "ended":
            return batch.id, True
        time.sleep(POLL_SECONDS)
    return batch.id, False


def collect(batch_id):
    """Results in ARRIVAL order. Never assume it equals submission order."""
    return list(get_client().messages.batches.results(batch_id))


def rows_from_entries(by_id, ttl="1h"):
    rows = {}
    for custom_id, entry in by_id.items():
        if entry.result.type == "succeeded":
            rows[custom_id] = row_from(entry.result.message, custom_id, batch=True, ttl=ttl)
    return rows


def join_positional(invoices, entries):
    """THE BUG: pair the i-th invoice with the i-th result. Valid only if results came back in submission order."""
    pairs = []
    for inv, entry in zip(invoices, entries):
        verdict = parse_verdict(text_of(entry.result.message)) if entry.result.type == "succeeded" else None
        pairs.append((inv, verdict))
    return pairs


# ================================================================ STAGES
def stage1(invoices, truth):
    """Meter it: a usage ledger and a monthly projection."""
    policy = load_policy("full")
    salt = new_salt()
    prefix = tokens_estimate(system_text(policy, salt))
    hr(f"{len(invoices)} invoices, the full policy re-sent on every request (no caching)")
    rows_by_model = {}
    for alias, model, subset in (("fast", MODEL_FAST, invoices), ("balanced", MODEL_BALANCED, invoices[:3])):
        rows = run_sequence(model, policy, subset, salt, f"baseline-{alias}")
        rows_by_model[alias] = rows
        print(f"--- {alias} ({model}), first 4 requests ---")
        print_rows(rows, limit=4)
        t = totals(rows)
        right, n = accuracy(rows, truth)
        print(f"{alias} total: {t['requests']} requests | input {t['total_in']:,} tok (cache write {t['cache_write']:,}, read {t['cache_read']:,}) | output {t['output']:,} | ${t['cost']:.4f}")
        print(f"verdicts parsed {sum(1 for r in rows if r.verdict)}/{n}; match ground truth {right}/{n}")
    fast = totals(rows_by_model["fast"])
    share = prefix / max(1, fast["total_in"] // fast["requests"])
    print(f"\nthe policy is about {100 * share:.0f}% of every request, and every request pays full price for it")
    hr(f"projection to {MONTHLY:,} invoices a month (measured average per request x volume)")
    print(f"{'model':<10}{'$/request':>11}{'$/month':>11}{'$/year':>12}")
    projected = {}
    for alias, rows in rows_by_model.items():
        per = totals(rows)["cost"] / len(rows)
        projected[alias] = per * MONTHLY
        print(f"{alias:<10}{per:>11.5f}{per * MONTHLY:>11,.0f}{per * MONTHLY * 12:>12,.0f}")
    save("stage1.json", {"requests": fast["requests"], "cache_read": fast["cache_read"] + totals(rows_by_model["balanced"])["cache_read"],
                         "parsed": sum(1 for r in rows_by_model["fast"] if r.verdict), "monthly": projected,
                         "prefix_tokens": fast["total_in"] // fast["requests"]})


def stage2(invoices, truth):
    """Count before you send: count_tokens and a budget gate."""
    policy = load_policy("full")
    salt = new_salt()
    requests = [build_request(MODEL_FAST, policy, inv, salt) for inv in invoices]
    counts = [HOOKS["count_request_tokens"](r) for r in requests]
    ceiling = int(max(counts) * 1.2)
    hr("count_tokens is free and sees the exact request body")
    for inv, n in list(zip(invoices, counts))[:4]:
        print(f"{inv['invoice_id']:<15}{n:>8,} tokens")
    print(f"... the largest of {len(counts)} is {max(counts):,}; the ceiling is set 20% above it: {ceiling:,} tokens")
    hr("the gate in front of every send")
    big = oversized_invoice(load_invoices()[0])
    decisions = []
    for inv in (invoices[0], big):
        n = HOOKS["count_request_tokens"](build_request(MODEL_FAST, policy, inv, salt))
        allowed = n <= ceiling
        decisions.append({"invoice_id": inv["invoice_id"], "tokens": n, "allowed": allowed})
        print(f"{inv['invoice_id']:<15}{n:>9,} tokens  ->  " + ("allowed" if allowed else f"REFUSED: {n:,} > ceiling {ceiling:,}; route to manual review"))
    hr("what the same tokens would cost, by model (input only, no cache)")
    for alias, model in (("fast", MODEL_FAST), ("balanced", MODEL_BALANCED)):
        price = PRICE_PER_MTOK[model][0]
        print(f"{alias:<10}${counts[0] * price / 1e6:.5f} per request of {counts[0]:,} input tokens -> ${counts[0] * price / 1e6 * MONTHLY:,.0f} a month before output")
    print("\ncount_tokens returns an estimate, is rate-limited separately from messages, and does not use caching.")
    save("stage2.json", {"counts": counts, "ceiling": ceiling, "decisions": decisions})


def stage3(invoices, truth, include_floor=False):
    """Cache the prefix, break it silently, diagnose it, fix it."""
    policy = load_policy("full")
    fast = MODEL_FAST
    first = invoices[:5]
    out = {}
    hr("A. caching on, nothing volatile in the prefix (first 5 invoices)")
    healthy = run_sequence(fast, policy, first, new_salt(), "healthy", cache=True)
    print_rows(healthy)
    print(f"first request writes ({healthy[0].cache_write:,}), later requests read: {[r.cache_read for r in healthy[1:]]}")
    out["healthy"] = {"write_first": healthy[0].cache_write, "reads_after": [r.cache_read for r in healthy[1:]]}

    hr("B. FAILURE: an audit stamp (request id + timestamp) is added to the TOP of the system prompt")
    salt = new_salt()
    broken_requests = [build_request(fast, policy, inv, salt, cache=True, stamp_in="system") for inv in first]
    broken = [send(r, inv["invoice_id"], f"broken:{inv['invoice_id']}") for r, inv in zip(broken_requests, first)]
    print_rows(broken)
    plain = run_sequence(fast, policy, first, new_salt(), "nocache")
    tb, tp = totals(broken), totals(plain)
    print(f"no error, no warning. cache_read total = {tb['cache_read']}. 5-request cost: broken cache ${tb['cost']:.4f} vs no caching at all ${tp['cost']:.4f}"
          f" -> {100 * (tb['cost'] / tp['cost'] - 1):+.0f}% (every call pays the cache-write surcharge)")
    out["broken"] = {"cache_read_total": tb["cache_read"], "cost": tb["cost"], "nocache_cost": tp["cost"]}

    hr("C. DIAGNOSE: compare the cacheable prefix of two consecutive requests")
    identical, report = diff_prefixes(broken_requests[0], broken_requests[1])
    print(report)
    out["diff"] = {"identical": identical, "report": report}

    hr("D. FIX: the same stamp moves into the user turn, after the cache breakpoint (all invoices)")
    fixed = run_sequence(fast, policy, invoices, new_salt(), "fixed", cache=True, stamp_in="user")
    print_rows(fixed, limit=4)
    reads = sum(1 for r in fixed if r.cache_read > 0)
    fixed_requests = [build_request(fast, policy, inv, "same", cache=True, stamp_in="user") for inv in invoices[:2]]
    print(diff_prefixes(fixed_requests[0], fixed_requests[1])[1])
    print(f"cache_read > 0 on {reads} of {len(fixed)} requests (the first one is always the write)")
    base = run_sequence(fast, policy, invoices, new_salt(), "nocache-all")
    tf, tn = totals(fixed), totals(base)
    print(f"\n{'configuration':<36}{'cache read':>11}{'cost':>10}")
    for name, t in (("no caching (stage 1)", tn), ("caching, stamp in system (broken)", tb), ("caching, stamp in user (fixed)", tf)):
        print(f"{name:<36}{t['cache_read']:>11,}{'$' + format(t['cost'], '.4f'):>10}")
    out["fixed"] = {"reads": reads, "requests": len(fixed), "cost": tf["cost"], "nocache_cost": tn["cost"]}
    if include_floor:
        hr("E. the OTHER silent no-cache: a prefix below the model's floor (the short 'lite' policy)")
        lite = load_policy("lite")
        print(f"lite policy ~{tokens_estimate(lite):,} tokens: the floor is {CACHE_FLOOR.get('sonnet', 512)} tokens for both models")
        for alias, model in (("fast", MODEL_FAST), ("balanced", MODEL_BALANCED)):
            rows = run_sequence(model, lite, invoices[:3], new_salt(), f"floor-{alias}", cache=True)
            print(f"{alias:<10}cache write/read per request: " + ", ".join(f"{r.cache_write}/{r.cache_read}" for r in rows))
        print("0/0 on every request would mean the marker was silently ignored (prefix below the floor).")
    save("stage3.json", out)


def stage4(invoices, truth, collect_id=None):
    """Batch it: submit, poll, collect, and join on custom_id."""
    policy = load_policy("full")
    fast = MODEL_FAST
    salt = new_salt()
    if collect_id:
        batch_id, ended = collect_id, True
    else:
        hr(f"A. submit {len(invoices)} invoices as one batch (cache_control with a 1-hour lifetime on the policy)")
        requests = HOOKS["batch_requests"]([inv["invoice_id"] for inv in invoices],
                                           [build_request(fast, policy, inv, salt, cache=True, ttl="1h") for inv in invoices])
        batch_id, ended = submit_and_wait(requests)
    if not ended:
        save("stage4_pending.json", {"batch_id": batch_id})
        print(f"\nThe batch has not ended yet (batches can take up to 24 hours). Collect it later with:  --stage 4 --collect {batch_id}")
        return
    entries = collect(batch_id)
    order = [e.custom_id for e in entries]
    print(f"results received: {len(entries)}; arrival order equals submission order? {order == [i['invoice_id'] for i in invoices]}")
    hr("B. FAILURE: join by position (the same results delivered in a different order, as the API allows)")
    shuffled = list(entries)
    random.Random(7).shuffle(shuffled)
    pairs = join_positional(invoices, shuffled)
    wrong = [(inv, v) for inv, v in pairs if v is None or v["invoice_id"] != inv["invoice_id"]]
    print(f"pairings where the verdict belongs to a DIFFERENT invoice: {len(wrong)} of {len(pairs)}")
    for inv, v in wrong[:3]:
        print(f"  {inv['invoice_id']} got the verdict of {v['invoice_id'] if v else '(none)'}")
    print("No exception, no warning: ten results for ten invoices looks perfect.")
    hr("C. FIX: join on custom_id, then check completeness and the echoed invoice_id")
    by_id = HOOKS["join_by_custom_id"](entries)
    rows = rows_from_entries(by_id)
    mismatch = [cid for cid, r in rows.items() if not r.verdict or r.verdict["invoice_id"] != cid]
    missing = sorted({i["invoice_id"] for i in invoices} - set(rows))
    joined_ok = len(rows) == len(invoices) and not mismatch and not missing
    right, n = accuracy(list(rows.values()), truth)
    print(f"joined {len(rows)} of {len(invoices)} | missing {len(missing)} | echo mismatches {len(mismatch)} -> {'PASS' if joined_ok else 'FAIL'}")
    print(f"verdicts matching ground truth: {right}/{n}")
    hr("D. measured cost of the same invoices, four ways (fast model)")
    normal = totals(run_sequence(fast, policy, invoices, new_salt(), "normal"))
    cached = totals(run_sequence(fast, policy, invoices, new_salt(), "cached", cache=True, stamp_in="user"))
    bc = totals(list(rows.values()))
    print(f"{'strategy':<14}{'c.write':>9}{'c.read':>10}{'cost':>10}{'vs normal':>11}")
    table = [("normal", normal), ("cached", cached), ("batch+cache", bc)]
    for name, t in table:
        print(f"{name:<14}{t['cache_write']:>9,}{t['cache_read']:>10,}{'$' + format(t['cost'], '.4f'):>10}{100 * (t['cost'] / normal['cost'] - 1):>+10.0f}%")
    print("(plain batch, without caching, would cost exactly half of normal: the discount is a flat 50%.)")
    prefix = normal["total_in"] // normal["requests"] - 350
    variable, output = 350, normal["output"] // normal["requests"]
    print()
    proj = projection({"fast": MODEL_FAST, "balanced": MODEL_BALANCED}, prefix, variable, output)
    print_projection(proj, f"E. projection at {MONTHLY:,} invoices a month (prefix {prefix:,} + tail {variable} + output {output} tokens per request)")
    print(f"\nbreak-even hit rate: 1-hour write {breakeven_hit_rate('1h'):.0%}, 5-minute write {breakeven_hit_rate('5m'):.0%}. Below it, caching costs MORE than not caching.")
    print("Real batches are best-effort for caching (typically 30% to 98% hits), so the table assumes 50%. Batch trades latency (up to 24 hours) for a flat 50% discount.")
    save("stage4.json", {"batch_id": batch_id, "positional_wrong": len(wrong), "joined": len(rows), "joined_ok": joined_ok,
                         "cost": {name: t["cost"] for name, t in table}, "cache_read_batch": bc["cache_read"],
                         "projection": [{k: r[k] for k in ("alias", "strategy", "monthly")} for r in proj]})
