"""procurement_core.py - the plumbing of Lab 2.4. You do not edit this file.

It holds everything around your six pieces of lab.py: the gate that every tool call passes (401, 403), the audit log, the HTTP
authentication layer, the helpers that start the server and talk to it with a real MCP client, and the six stage runners.
The server is always started the same safe way: sys.executable plus the absolute path of lab.py, so it does not depend on a shell,
a virtual-environment launcher or the current folder.
"""
import asyncio
import contextlib
import hmac
import json
import logging
import os
import pathlib
import secrets
import socket
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.request
from typing import NamedTuple

HERE = pathlib.Path(__file__).resolve().parent
LAB = HERE / "lab.py"
EVIDENCE = HERE / "evidence"
ROLE_ENV = {"analyst": "PROC_KEY_ANALYST", "approver": "PROC_KEY_APPROVER"}
USERS = {"analyst": "dev.analyst", "approver": "maya.approver"}
MASK = "***REDACTED***"
MIN_KEY_LEN = 16
HOOKS = {}  # your pieces, filled in by configure() at the bottom of lab.py
STATE = {"auth": False, "principal": None, "sink": None}  # the server's switches; sink collects audit lines for a stage to inspect


def configure(**hooks):
    HOOKS.update(hooks)


class Principal(NamedTuple):
    user: str
    role: str


class ProcError(Exception):
    """A business-rule failure with a stable machine-readable code, never a stack trace."""

    def __init__(self, code, message, status=None):
        super().__init__(message)
        self.code, self.message, self.status = code, message, status


# ================================================================ server side: results, audit log, gate
def ok(data):
    from mcp.types import CallToolResult, TextContent
    return CallToolResult(content=[TextContent(type="text", text=json.dumps(data, sort_keys=True))], structured_content=data)


def fail(code, message, status=None):
    from mcp.types import CallToolResult, TextContent
    error = {"code": code, "message": message, **({"status": status} if status else {})}
    return CallToolResult(is_error=True, content=[TextContent(type="text", text=json.dumps({"error": error}, sort_keys=True))],
                          structured_content={"error": error})


def audit(event, **fields):
    """One JSON line per event, to stderr (stdout is the protocol channel). YOUR redact() runs on every line."""
    line = HOOKS["redact"](json.dumps({"event": event, **fields}, sort_keys=True, default=str))
    if STATE["sink"] is not None:  # a stage is collecting the lines instead of printing them
        STATE["sink"].append(line)
        return
    sys.stderr.write(line + "\n")
    sys.stderr.flush()


def principal_of(ctx):
    """stdio: the one caller, fixed at startup. HTTP: the principal the auth layer put on this request."""
    if STATE["principal"] is not None:
        return STATE["principal"]
    request = getattr(getattr(ctx, "request_context", None), "request", None)
    return request.scope.get("proc.principal") if request is not None else None


def who(ctx):
    """(user, role) of the caller, or an open-access placeholder while authentication is off."""
    principal = principal_of(ctx)
    return (principal.user, principal.role) if principal else ("open-access", "open")


def run(ctx, tool, work):
    """The gate every tool passes: 401 if nobody, 403 if the role may not call it, else run work() and turn a ProcError into a result."""
    principal = principal_of(ctx)
    if STATE["auth"] and principal is None:
        audit("tool_call", tool=tool, outcome="denied_unauthenticated", role="anonymous")
        return fail("unauthenticated", "No authenticated principal for this call", 401)
    if STATE["auth"] and not HOOKS["is_allowed"](principal.role, tool):
        audit("tool_call", tool=tool, outcome="denied_forbidden", role=principal.role)
        return fail("forbidden", f"Role '{principal.role}' is not permitted to call {tool}", 403)
    try:
        result = ok(work())
        audit("tool_call", tool=tool, outcome="ok", role=who(ctx)[1])
    except ProcError as e:
        result = fail(e.code, e.message, e.status)
        audit("tool_call", tool=tool, outcome=f"error_{e.code}", role=who(ctx)[1])
    return result


# ================================================================ keys
def load_keyring():
    """role -> key, from the environment. Fails closed: no keys, or a short key, and the server refuses to start."""
    ring = {role: os.environ[name] for role, name in ROLE_ENV.items() if os.environ.get(name)}
    if not ring:
        refuse("no PROC_KEY_* variables are set")
    if any(len(key) < MIN_KEY_LEN for key in ring.values()):
        refuse(f"a key is shorter than {MIN_KEY_LEN} characters")
    return ring


def known_secrets():
    """The credential values of THIS process, longest first, so overlapping values are masked completely."""
    names = [*ROLE_ENV.values(), "PROC_API_KEY"]
    return sorted({os.environ[name] for name in names if os.environ.get(name)}, key=len, reverse=True)


def make_keys():
    """Throw-away keys for one stage run. They live in this process and its children, and are never printed or saved."""
    keys = {"analyst": "prk_an_" + secrets.token_urlsafe(18), "approver": "prk_ap_" + secrets.token_urlsafe(18)}
    os.environ.update({ROLE_ENV[role]: key for role, key in keys.items()})
    return keys


def refuse(message):
    print(f"procurement: refusing to start: {message}", file=sys.stderr)
    raise SystemExit(2)


# ================================================================ HTTP authentication layer (ASGI)
def bearer_token(header):
    parts = (header or "").split(None, 1)
    return parts[1].strip() if len(parts) == 2 and parts[0].lower() == "bearer" else ""


class BearerAuthMiddleware:
    """Answer 401 unless your authenticate() accepts the Bearer key. The 401 is identical for every failure."""

    def __init__(self, app):
        self.app = app

    async def __call__(self, scope, receive, send):
        if scope["type"] != "http":  # lifespan must pass through, or the MCP session manager never starts
            return await self.app(scope, receive, send)
        header = {k.decode().lower(): v.decode("latin-1") for k, v in scope["headers"]}.get("authorization", "")
        role = HOOKS["authenticate"](bearer_token(header))
        if role:
            scope["proc.principal"] = Principal(USERS[role], role)
            return await self.app(scope, receive, send)
        audit("auth_failed", authorization=header)  # a debug line, as written while chasing a 401: it holds whatever the caller sent
        body = b'{"error":"unauthorized"}'
        await send({"type": "http.response.start", "status": 401, "headers": [
            (b"content-type", b"application/json"), (b"content-length", str(len(body)).encode()), (b"www-authenticate", b'Bearer realm="procurement"')]})
        await send({"type": "http.response.body", "body": body})


class AccessLogMiddleware:
    """Outermost layer: method, path, status and role of every request. Never headers."""

    def __init__(self, app):
        self.app = app

    async def __call__(self, scope, receive, send):
        if scope["type"] != "http":
            return await self.app(scope, receive, send)
        status = {"code": 0}

        async def send_and_note(message):
            if message["type"] == "http.response.start":
                status["code"] = message["status"]
            await send(message)

        try:
            await self.app(scope, receive, send_and_note)
        finally:
            principal = scope.get("proc.principal")
            audit("http_access", method=scope["method"], path=scope["path"], status=status["code"], role=principal.role if principal else "anonymous")


# ================================================================ starting the server (python lab.py --serve ...)
def use_binary_stdio():
    """On Windows, stop the C runtime from rewriting newlines on the protocol channel."""
    if os.name == "nt":
        import msvcrt
        msvcrt.setmode(sys.stdin.fileno(), os.O_BINARY)
        msvcrt.setmode(sys.stdout.fileno(), os.O_BINARY)


def serve(mcp, args):
    use_binary_stdio()
    HOOKS["setup_logging"]()
    if args.auth == "on":
        load_keyring()
        STATE["auth"] = True
        if args.transport == "stdio":
            role = HOOKS["authenticate"](os.environ.get("PROC_API_KEY", ""))
            if role is None:
                refuse("PROC_API_KEY is missing or not a registered key")
            STATE["principal"] = Principal(USERS[role], role)
    if args.transport == "stdio":
        mcp.run(transport="stdio")
        return
    if not STATE["auth"]:
        refuse("the HTTP transport must run with --auth on")
    import uvicorn
    uvicorn.run(AccessLogMiddleware(BearerAuthMiddleware(mcp.streamable_http_app())), host="127.0.0.1", port=args.port, log_level="warning")


# ================================================================ client side: talk to the server with a real MCP client
def flat(exc):
    """Yield the leaf exceptions of nested exception groups."""
    inner = getattr(exc, "exceptions", None)
    if inner:
        for e in inner:
            yield from flat(e)
    else:
        yield exc


class ClientLog(logging.Handler):
    """Collects what the MCP client logs in this process (it logs JSON-RPC parse errors)."""

    def __init__(self):
        super().__init__(level=logging.DEBUG)
        self.messages = []

    def emit(self, record):
        self.messages.append(record.getMessage())

    def __enter__(self):
        logging.getLogger().addHandler(self)
        return self

    def __exit__(self, *exc):
        logging.getLogger().removeHandler(self)

    @property
    def parse_errors(self):
        return sum("Failed to parse" in m for m in self.messages)


LAST_STDERR = {"text": ""}  # what the last stdio server wrote to stderr: the first place to look when a connection fails


@contextlib.asynccontextmanager
async def stdio_session(auth="off", role=None, init_timeout=8.0):
    """Start `python lab.py --serve` as a stdio MCP server and yield an initialized session."""
    from mcp import ClientSession, StdioServerParameters, stdio_client
    env = {**os.environ, "PYTHONUNBUFFERED": "1", "PYTHONIOENCODING": "utf-8"}
    env.pop("PROC_API_KEY", None)
    if role:
        env["PROC_API_KEY"] = os.environ[ROLE_ENV[role]]
    params = StdioServerParameters(command=sys.executable, args=[str(LAB), "--serve", "--transport", "stdio", "--auth", auth], env=env, cwd=str(HERE))
    with tempfile.TemporaryFile(mode="w+") as errlog:  # a real file: the child needs a handle for its stderr; closed (and deleted) on exit
        try:
            async with stdio_client(params, errlog=errlog) as (read, write):
                async with ClientSession(read, write) as session:
                    await asyncio.wait_for(session.initialize(), timeout=init_timeout)
                    yield session
        finally:
            errlog.seek(0)
            LAST_STDERR["text"] = errlog.read()


@contextlib.asynccontextmanager
async def http_session(url, key=None):
    import httpx2
    from mcp import ClientSession
    from mcp.client.streamable_http import streamable_http_client
    headers = {"Authorization": f"Bearer {key}"} if key else {}
    async with httpx2.AsyncClient(headers=headers, timeout=20.0) as http_client:
        async with streamable_http_client(url, http_client=http_client) as streams:
            async with ClientSession(streams[0], streams[1]) as session:
                await session.initialize()
                yield session


class HttpServer:
    """`with HttpServer() as server:` runs lab.py over streamable HTTP on a free port, and always stops it."""

    def __init__(self):
        s = socket.socket()
        s.bind(("127.0.0.1", 0))
        self.port = s.getsockname()[1]
        s.close()
        self.stderr = tempfile.TemporaryFile(mode="w+b")
        self.proc = None

    @property
    def url(self):
        return f"http://127.0.0.1:{self.port}/mcp"

    def __enter__(self):
        command = [sys.executable, str(LAB), "--serve", "--transport", "http", "--auth", "on", "--port", str(self.port)]
        self.proc = subprocess.Popen(command, cwd=str(HERE), env={**os.environ, "PYTHONUNBUFFERED": "1"}, stdout=subprocess.DEVNULL, stderr=self.stderr)
        try:
            self.wait_until_serving()
        except BaseException:
            self.stop()
            raise
        return self

    def wait_until_serving(self):
        for _ in range(150):
            if self.proc.poll() is not None:
                raise RuntimeError("the server exited early: " + self.log_text()[-300:])
            try:
                urllib.request.urlopen(self.url, timeout=1)
                return
            except urllib.error.HTTPError:
                return  # any HTTP answer, even 401, means the socket is serving
            except OSError:
                time.sleep(0.15)
        raise RuntimeError("the server never became ready")

    def log_text(self):
        self.stderr.flush()
        self.stderr.seek(0)
        return self.stderr.read().decode("utf-8", "replace")

    def stop(self):
        """Stop the process first, close the log handle second, and never fail on cleanup."""
        if self.proc is not None and self.proc.poll() is None:
            self.proc.terminate()
            try:
                self.proc.wait(5)
            except subprocess.TimeoutExpired:
                self.proc.kill()
                self.proc.wait(5)
        with contextlib.suppress(PermissionError, OSError):
            self.stderr.close()

    def __exit__(self, *exc):
        self.stop()
        return False


def raw_status(url, key):
    """The raw HTTP view of a request. The MCP client hides the status of a 401."""
    request = urllib.request.Request(url, headers={"Authorization": f"Bearer {key}"} if key else {})
    try:
        return str(urllib.request.urlopen(request, timeout=5).status)
    except urllib.error.HTTPError as e:
        return f"{e.code} {e.headers.get('WWW-Authenticate')}"


# ================================================================ the six stages
def show(label, good, hint=""):
    print(f"  {'ok  ' if good else 'TODO'}  {label}" + ("" if good else f"   <- {hint}" if hint else ""))
    return good


def save(stage, facts):
    EVIDENCE.mkdir(exist_ok=True)
    (EVIDENCE / f"stage{stage}.json").write_text(json.dumps({"stage": stage, **facts}, indent=1, default=str), encoding="utf-8")


def code_of(result):
    return ((result.structured_content or {}).get("error") or {}).get("code")


def schema_note(result):
    data = result.structured_content or {}
    return data.get("error") or ("rejected by the schema, before our code ran" if result.is_error else {k: data[k] for k in sorted(data) if k in ("id", "count", "status")})


async def stage1():
    print("== Stage 1: a stdio server, and the stdout trap ==")
    facts = {"initialized": False, "parse_errors": 0, "log_lines": 0, "tools": []}
    with ClientLog() as client_log:
        try:
            async with stdio_session() as session:
                facts["tools"] = sorted(t.name for t in (await session.list_tools()).tools)
                found = await asyncio.wait_for(session.call_tool("find_supplier", {"query": "ind"}), 10)
                facts["initialized"], facts["find_supplier_ok"] = True, not found.is_error
        except BaseException as e:  # noqa: BLE001 - the failure is the lesson
            leaf = next(iter(flat(e)))
            print(f"  initialize FAILED ({type(leaf).__name__}): the server answered, but the reply was never parsed")
    facts["parse_errors"] = client_log.parse_errors
    facts["log_lines"] = sum("procurement" in line for line in LAST_STDERR["text"].splitlines())
    show("the client connected and called find_supplier", facts["initialized"],
         "the first thing the server wrote to stdout was not JSON-RPC; read setup_logging (TODO 1)")
    show("the client saw no JSON-RPC parse error", facts["initialized"] and facts["parse_errors"] == 0)
    show("the server's own log lines arrived on stderr", facts["log_lines"] >= 1, "log to sys.stderr, never print")
    if facts["initialized"]:
        print("  tools:", facts["tools"])
    return facts


async def stage2():
    print("== Stage 2: resources ==")
    facts = {"fixed": [], "templates": [], "po_read": False, "bad_id_error": False, "session_alive": False, "supplier_masked": False}
    async with stdio_session() as session:
        facts["fixed"] = sorted(r.uri for r in (await session.list_resources()).resources)
        facts["templates"] = sorted(t.uri_template for t in (await session.list_resource_templates()).resource_templates)
        print("  resources/list           ->", facts["fixed"])
        print("  resources/templates/list ->", facts["templates"])
        supplier = (await session.read_resource("supplier://S-100")).contents[0].text
        facts["supplier_masked"] = "****" in supplier and "DE89370400440532013000" not in supplier
        print("  supplier://S-100 ->", supplier[:96], "...")
        try:
            text = (await session.read_resource("po://PO-2001")).contents[0].text
            facts["po_read"] = "PO-2001" in text and "approvals" in text
            print("  po://PO-2001 ->", text[:96], "...")
        except Exception as e:  # noqa: BLE001
            print(f"  po://PO-2001 -> {type(e).__name__}: the po:// template is not there yet (TODO 2)")
        try:
            await session.read_resource("po://PO-9999")
        except Exception as e:  # noqa: BLE001
            facts["bad_id_error"] = True
            print(f"  po://PO-9999 -> {type(e).__name__}: an error, not a crash")
        facts["session_alive"] = not (await session.call_tool("find_supplier", {"query": "ind"})).is_error
    show("the po://{po_id} template is listed", "po://{po_id}" in facts["templates"], "add the resource template (TODO 2)")
    show("po://PO-2001 returns the purchase order with its approvals", facts["po_read"], "TODO 2")
    show("an unknown id is an error and the session survives", facts["bad_id_error"] and facts["session_alive"], "raise ValueError for an unknown id (TODO 2)")
    show("the supplier resource masks the bank account", facts["supplier_masked"])
    return facts


async def stage3():
    print("== Stage 3: validated tools and structured errors ==")
    facts = {"calls": {}, "tools": [], "po_pattern": None, "prompt_ok": False}
    calls = [("get_po PO-2002", "get_po", {"po_id": "PO-2002"}), ("get_po PO-9999 (unknown)", "get_po", {"po_id": "PO-9999"}),
             ("get_po 'po-1' (bad format)", "get_po", {"po_id": "po-1"}),
             ("approve_po PO-2004 (supplier suspended)", "approve_po", {"po_id": "PO-2004"}), ("approve_po PO-2002 (already approved)", "approve_po", {"po_id": "PO-2002"}),
             ("approve_po PO-2001 (valid, auth is off)", "approve_po", {"po_id": "PO-2001"}), ("unknown tool delete_po", "delete_po", {"po_id": "PO-2001"})]
    async with stdio_session() as session:
        tools = {t.name: t for t in (await session.list_tools()).tools}
        facts["tools"] = sorted(tools)
        if "get_po" in tools:
            facts["po_pattern"] = tools["get_po"].input_schema["properties"]["po_id"].get("pattern")
        print("  tools:", facts["tools"], "| get_po po_id pattern:", facts["po_pattern"])
        for label, name, arguments in calls:
            result = await session.call_tool(name, arguments)
            facts["calls"][label] = {"is_error": result.is_error, "code": code_of(result), "structured": result.structured_content}
            print(f"  {label:<44} is_error={result.is_error!s:<5} {schema_note(result)}")
        prompt = await session.get_prompt("review_po", {"po_id": "PO-2001"})
        facts["prompt_ok"] = "po://PO-2001" in prompt.messages[0].content.text
    c = facts["calls"]
    show("get_po returns a purchase order", c["get_po PO-2002"]["is_error"] is False, "add the get_po tool (TODO 3)")
    show("an unknown id gives the structured code po_not_found", c["get_po PO-9999 (unknown)"]["code"] == "po_not_found", "TODO 3")
    show("a badly formed id is rejected by the schema, before our code runs", facts["po_pattern"] is not None and c["get_po 'po-1' (bad format)"]["is_error"], "give po_id a pattern (TODO 3)")
    show("business rules give 422 and 409 codes", c["approve_po PO-2004 (supplier suspended)"]["code"] == "supplier_not_active" and c["approve_po PO-2002 (already approved)"]["code"] == "po_not_pending")
    show("an unknown tool is rejected", c["unknown tool delete_po"]["is_error"])
    return facts


async def stage4():
    print("== Stage 4: your own client, the host view, the config linter ==")
    facts = {"lint": {}}
    async with stdio_session() as session:
        tools = (await session.list_tools()).tools
        print("  tools:", sorted(t.name for t in tools), "| resources:", [r.uri for r in (await session.list_resources()).resources],
              "| templates:", sorted(t.uri_template for t in (await session.list_resource_templates()).resource_templates),
              "| prompts:", [p.name for p in (await session.list_prompts()).prompts])
        print("  a host such as Claude Code shows the model:", sorted(f"mcp__procurement__{t.name}" for t in tools))
        facts["tools"] = sorted(t.name for t in tools)
    for name in ("mcp.stdio.json", "mcp.http.json", "mcp.leaky.json"):
        config = json.loads((HERE / "CONFIGS" / name).read_text(encoding="utf-8"))
        facts["lint"][name] = HOOKS["lint_config"](config)
        print(f"  {name}: {'PASS' if not facts['lint'][name] else 'FAIL'}" + ("   <- expected to fail" if "leaky" in name else ""))
        for problem in facts["lint"][name]:
            print("     -", problem)
    lint = facts["lint"]
    show("the shipped stdio and http configs pass", lint["mcp.stdio.json"] == [] and lint["mcp.http.json"] == [])
    show("the leaky config fails R2, R4 and R5", {"R2", "R4", "R5"} <= {p.split()[0] for p in lint["mcp.leaky.json"]}, "write lint_config (TODO 4)")
    return facts


async def call_asgi(app, headers):
    """Call an ASGI app in-process with one POST. Returns (status, body)."""
    sent = []

    async def receive():
        return {"type": "http.request", "body": b"{}", "more_body": False}

    async def send(message):
        sent.append(message)

    scope = {"type": "http", "method": "POST", "path": "/mcp", "headers": [(k.lower().encode(), v.encode()) for k, v in headers.items()]}
    await app(scope, receive, send)
    return sent[0]["status"], b"".join(m.get("body", b"") for m in sent[1:]).decode()


async def reached_app(scope, receive, send):
    """Stands in for the MCP app: 200 for anything that got past authentication."""
    if scope["type"] == "http":
        await send({"type": "http.response.start", "status": 200, "headers": []})
        await send({"type": "http.response.body", "body": b"reached the MCP app"})


async def edge_checks(keys):
    print("\n  [1] authentication at the HTTP edge: who are you?")
    STATE["sink"] = []
    app = BearerAuthMiddleware(reached_app)
    cases = [("no Authorization header", {}), ("Basic instead of Bearer", {"Authorization": "Basic dXNlcjpwYXNz"}),
             ("Bearer with an empty token", {"Authorization": "Bearer "}), ("Bearer, wrong key", {"Authorization": "Bearer not-a-registered-key-0123456789"}),
             ("Bearer, approver key plus one character", {"Authorization": f"Bearer {keys['approver']}x"}),
             ("Bearer, analyst key", {"Authorization": f"Bearer {keys['analyst']}"}), ("Bearer, approver key", {"Authorization": f"Bearer {keys['approver']}"})]
    statuses, bodies = [], set()
    for label, headers in cases:
        status, body = await call_asgi(app, headers)
        statuses.append(status)
        print(f"      {label:<42} -> {status}")
        if status == 401:
            bodies.add(body)
    lines = STATE["sink"]
    STATE["sink"] = None
    leaked = [role for role, key in keys.items() if any(key in line for line in lines)]
    return statuses, bodies, lines, leaked


def work_per_attempt(keys):
    """Count the hmac.compare_digest calls made for the first key, the last key and an unknown key."""
    counts, real = [], hmac.compare_digest
    calls = {"n": 0}

    def counting(a, b):
        calls["n"] += 1
        return real(a, b)

    hmac.compare_digest = counting
    try:
        for token in (keys["analyst"], keys["approver"], "x" * 30):
            calls["n"] = 0
            HOOKS["authenticate"](token)
            counts.append(calls["n"])
    finally:
        hmac.compare_digest = real
    return counts


async def role_matrix():
    matrix, forbidden = {}, None
    for role in ("analyst", "approver"):
        try:
            async with stdio_session(auth="on", role=role) as session:
                row = {"get_po": await session.call_tool("get_po", {"po_id": "PO-2002"}),
                       "approve_po": await session.call_tool("approve_po", {"po_id": "PO-2001"})}
        except BaseException:  # noqa: BLE001 - authenticate() is not written yet
            print(f"      the {role} server did not start: {LAST_STDERR['text'].strip()[-100:]}")
            return None, None
        matrix[role] = {tool: result.is_error for tool, result in row.items()}
        if role == "analyst":
            forbidden = (row["approve_po"].structured_content or {}).get("error")
    return matrix, forbidden


def startup_refusals():
    codes = []
    for label, drop in (("no PROC_API_KEY", {"PROC_API_KEY"}), ("no keys at all", {"PROC_API_KEY", *ROLE_ENV.values()})):
        env = {k: v for k, v in os.environ.items() if k not in drop}
        done = subprocess.run([sys.executable, str(LAB), "--serve", "--auth", "on"], cwd=str(HERE), env=env, capture_output=True, text=True,
                              stdin=subprocess.DEVNULL, timeout=60)
        leaked = any(secret in done.stderr for secret in known_secrets())
        print(f"      {label:<18} -> exit {done.returncode} | key in stderr: {leaked}")
        codes.append(done.returncode == 2 and not leaked)
    return all(codes)


async def stage5():
    print("== Stage 5: authentication, roles, safe logging ==")
    keys = make_keys()
    statuses, bodies, lines, leaked = await edge_checks(keys)
    print("\n  [2] constant work: the number of comparisons must not depend on the answer")
    counts = work_per_attempt(keys)
    print("      comparisons for first key, last key, unknown key:", counts)
    print("\n  [3] roles: are you allowed to do that? (a real stdio server per role)")
    matrix, forbidden = await role_matrix()
    if matrix:
        print("      analyst: get_po", "DENIED" if matrix["analyst"]["get_po"] else "ok", "| approve_po", "DENIED" if matrix["analyst"]["approve_po"] else "ok")
        print("      approver: get_po", "DENIED" if matrix["approver"]["get_po"] else "ok", "| approve_po", "DENIED" if matrix["approver"]["approve_po"] else "ok")
    print("\n  [4] grep the log for the keys (the server logs the Authorization header of a rejected request)")
    print("      keys found in the log:", leaked or "none", "| lines:", len(lines))
    print("      sample:", next((line for line in lines if keys["approver"][:10] in line or MASK in line), "(no line)").replace(keys["approver"], "<APPROVER KEY>")[:110])
    print("\n  [5] startup is refused without a key")
    refused = startup_refusals()
    facts = {"statuses": statuses, "distinct_401_bodies": len(bodies), "counts": counts, "matrix": matrix, "forbidden": forbidden, "keys_in_log": leaked, "refused": refused}
    show("five failures give 401 and both valid keys get through", statuses == [401] * 5 + [200, 200], "write authenticate (TODO 5)")
    show("the 401 body is the same for every failure", len(bodies) == 1)
    show("every key is compared, whatever the answer", len(set(counts)) == 1 and counts[0] >= 2, "compare every key with hmac.compare_digest, no early return (TODO 5)")
    show("analyst reads but cannot approve; approver can", matrix is not None and not matrix["analyst"]["get_po"] and matrix["analyst"]["approve_po"] and not matrix["approver"]["approve_po"],
         "fill ROLE_TOOLS and is_allowed (TODO 5)")
    show("the refusal is a tool result with status 403", (forbidden or {}).get("status") == 403 and forbidden.get("code") == "forbidden")
    show("no key appears in the log", not leaked, "mask the keys and Bearer tokens in redact (TODO 6)")
    show("startup without a key exits with code 2 and prints no key", refused)
    return facts


async def same_workflow(session):
    """One workflow. The listing and the results must be identical on every transport."""
    tools = sorted(t.name for t in (await session.list_tools()).tools)
    po = await session.call_tool("get_po", {"po_id": "PO-2002"})
    suppliers = await session.call_tool("find_supplier", {"query": "ind", "category": "maintenance"})
    return [f"tools {tools}", f"get_po status {(po.structured_content or {}).get('status')}", f"find_supplier count {(suppliers.structured_content or {}).get('count')}"]


async def client_view(label, url, key):
    """What the SDK client shows for a rejected key. In SDK 2.3.0 the HTTP status is not visible."""
    try:
        async with http_session(url, key) as session:
            await session.list_tools()
        return "connected"
    except BaseException as e:  # noqa: BLE001
        return f"{type(e).__name__}[{', '.join(type(x).__name__ + '(' + str(getattr(x, 'code', '')) + ')' for x in flat(e))}]"


def parse_line(line):
    """A JSON log line as a dict, or None for any other line (for example a logging message)."""
    try:
        return json.loads(line) if line.startswith("{") else None
    except ValueError:
        return None


async def stage6():
    print("== Stage 6: the same server over HTTP, and the denial demo ==")
    keys = make_keys()
    facts = {"identical": False, "analyst_denied": False, "approver_ok": False, "log_statuses": [], "keys_in_log": [], "denied_audited": False, "stopped": False}
    with HttpServer() as server:
        try:
            async with stdio_session(auth="on", role="approver") as session:
                over_stdio = await same_workflow(session)
            async with http_session(server.url, keys["approver"]) as session:
                over_http = await same_workflow(session)
            facts["identical"] = over_stdio == over_http
            print("  same client code over stdio and HTTP:", "\n    ".join(["", *over_http]).strip())
            async with http_session(server.url, keys["analyst"]) as session:
                denied = await session.call_tool("approve_po", {"po_id": "PO-2001"})
            facts["analyst_denied"] = code_of(denied) == "forbidden" and denied.structured_content["error"]["status"] == 403
            async with http_session(server.url, keys["approver"]) as session:
                approved = await session.call_tool("approve_po", {"po_id": "PO-2001"})
            facts["approver_ok"] = not approved.is_error
        except BaseException as e:  # noqa: BLE001
            print("  the HTTP session failed:", [type(x).__name__ for x in flat(e)], "(authenticate or ROLE_TOOLS not written yet?)")
        print("  rejected keys, client view:", await client_view("no key", server.url, None), "|", await client_view("wrong key", server.url, "wrong-key-0123456789abc"))
        print("  rejected keys, raw HTTP view:", raw_status(server.url, None), "|", raw_status(server.url, "wrong-key-0123456789abc"))
        raw_status(server.url, keys["approver"] + "x")  # a mistyped real key: the server logs the header it was sent
        log_text = server.log_text()
    facts["stopped"] = server.proc.poll() is not None
    events = [e for e in map(parse_line, log_text.splitlines()) if e]
    facts["log_statuses"] = sorted({e["status"] for e in events if e["event"] == "http_access"})
    facts["keys_in_log"] = [role for role, key in keys.items() if key in log_text]
    facts["denied_audited"] = any(e.get("outcome") == "denied_forbidden" for e in events if e["event"] == "tool_call")
    print("  server log: statuses", facts["log_statuses"], "| denied write audited:", facts["denied_audited"], "| keys in the log:", facts["keys_in_log"] or "none")
    show("the listing and the workflow are identical over stdio and HTTP", facts["identical"])
    show("the analyst is refused with 403 over HTTP; the approver succeeds", facts["analyst_denied"] and facts["approver_ok"], "authenticate and ROLE_TOOLS (TODO 5)")
    show("the log shows 401s and the audited denial", 401 in facts["log_statuses"] and facts["denied_audited"])
    show("no key appears in the server log", not facts["keys_in_log"], "redact (TODO 6)")
    show("the server process is gone afterwards", facts["stopped"])
    return facts


STAGES = {1: stage1, 2: stage2, 3: stage3, 4: stage4, 5: stage5, 6: stage6}


def run_stage(number):
    try:
        facts = asyncio.run(STAGES[number]())
    except BaseException as e:  # noqa: BLE001 - say what happened instead of printing a traceback
        leaves = [f"{type(x).__name__}: {x}" for x in flat(e)]
        print(f"\nStage {number} could not talk to the server: {leaves[0][:160]}")
        print("The server's stderr says:", LAST_STDERR["text"].strip()[-300:] or "(nothing)")
        print("Do the stages in order: a server that prints to stdout (TODO 1) breaks every stage after stage 1.")
        sys.exit(1)
    save(number, facts)
    print(f"\nSaved evidence/stage{number}.json. When all the stages you have done look right, run: python check.py")
