"""Plumbing for Lab 2.6 (use an MCP server). You do not edit this file.

It starts the team-notes server (notes_server.py), asks the same three questions at every stage, and prints ONE measured result per stage:

  stage 1  + your connection (TODO 1): the server describes its tools, and you call one by hand (no Claude)
  stage 2  + your conversion (TODO 2): the server's tools become the tool list Claude reads
  stage 3  + your result conversion and forwarding (TODOs 3, 4): Claude asks, the server answers, Claude replies
  stage 4  + your allow-list and guard (TODOs 5, 6): a newer server adds delete_note, and your client must not hand it over

The same loop as Lab 2.5 runs here, but the tool schemas and the tool functions now come from the server.
"""
import json
import pathlib
from types import SimpleNamespace

from claude_client import MODEL_BALANCED, ask

HERE = pathlib.Path(__file__).parent
EVIDENCE = HERE / "evidence"
HOOKS = {"open_session": None, "system": None, "mcp_tool_to_claude": None, "result_to_text": None, "answer": None, "offer": None}
STAGE_TITLES = {1: "your connection: look at the server, no Claude", 2: "your conversion: Claude sees the server's tools",
                3: "your forwarding: the server answers", 4: "your allow-list: a new tool is not handed over"}
QUESTIONS = [
    {"label": "on-call", "question": "Who is on call this week and what is the pager number?", "facts": [["555-0142"]]},
    {"label": "expense limit", "question": "What is the limit above which an expense needs approval?", "facts": [["75"]]},
    {"label": "unknown note", "question": "What does the note with id N-9 say?", "facts": None},
]


def configure(**pieces):
    HOOKS.update(pieces)


def hr(title):
    print("\n" + "=" * 100 + f"\n{title}\n" + "=" * 100)


def short(text, n=100):
    text = " ".join(str(text).split())
    return text if len(text) <= n else text[:n] + "..."


def grounded(text, facts):
    low = text.lower()
    return all(any(option.lower() in low for option in group) for group in facts)


def recorder(send=ask):
    """Wrap a send function so we can see the messages the loop sent. Returns (send, log)."""
    log = {"messages": []}

    def wrapped(messages, **kwargs):
        log["messages"] = messages
        return send(messages, **kwargs)
    return wrapped, log


def flagged_errors(messages):
    blocks = [b for m in messages if m["role"] == "user" and isinstance(m["content"], list) for b in m["content"] if isinstance(b, dict)]
    return sum(1 for b in blocks if b.get("type") == "tool_result" and b.get("is_error") is True)


def save(name, data):
    EVIDENCE.mkdir(exist_ok=True)
    (EVIDENCE / name).write_text(json.dumps(data, indent=2, default=str), encoding="utf-8")


def history(stage):
    lines = []
    for n in range(1, stage + 1):
        path = EVIDENCE / f"stage{n}.json"
        if path.exists():
            lines.append(f"  stage {n}: {json.loads(path.read_text(encoding='utf-8'))['score']}")
    print("\nprogress so far:\n" + "\n".join(lines))


async def converted_tools(session):
    """Ask the server for its tools and convert each one with YOUR function (TODO 1)."""
    claude_tools = [HOOKS["mcp_tool_to_claude"](t) for t in (await session.list_tools()).tools]
    if any(not t.get("name") or "input_schema" not in t for t in claude_tools):
        raise SystemExit("TODO 2 is not done: mcp_tool_to_claude does not return name, description and input_schema yet. Paste the snippet from the guide.")
    return claude_tools


# ---------------------------------------------------------------- stage 1: connect and look
async def stage1():
    async with HOOKS["open_session"]("notes_server.py") as session:
        tools = (await session.list_tools()).tools
        print(f"the server offers {len(tools)} tools:")
        for t in tools:
            print(f"  {t.name}({', '.join(t.input_schema.get('properties', {}))})  {short((t.description or '').splitlines()[0], 80)}")
        found = await session.call_tool("search_notes", {"query": "pager"})
        print(f"\ncall search_notes('pager')  -> is_error={found.is_error}  content[0].text = {short(found.content[0].text)}")
        try:
            missing = await session.call_tool("get_note", {"note_id": "N-9"})
            missing_flag, missing_text = bool(missing.is_error), missing.content[0].text if missing.content else ""
        except Exception as exc:  # noqa: BLE001 - some SDK versions raise instead of returning is_error
            missing_flag, missing_text = True, f"raised {type(exc).__name__}: {exc}"
        print(f"call get_note('N-9')        -> is_error={missing_flag}  content[0].text = {short(missing_text)}")
    score = f"{len(tools)} tools discovered, one call answered, one error carried as data (no crash)"
    print(f"\nRESULT: {score}. You wrote no tool schema and no tool function: the server provided both.")
    return {"tool_names": sorted(t.name for t in tools), "search_text": found.content[0].text, "missing_is_error": missing_flag, "score": score}


# ---------------------------------------------------------------- stage 2: the tools Claude sees
async def stage2():
    async with HOOKS["open_session"]("notes_server.py") as session:
        claude_tools = await converted_tools(session)
        print("the tool list Claude will read:")
        for t in claude_tools:
            print(f"  {t['name']}: required {t['input_schema'].get('required')}  keys {sorted(t)}")
        names = {t["name"] for t in claude_tools}
        rows = []
        print("\nfirst request from Claude for each question (nothing is forwarded to the server yet):")
        for q in QUESTIONS:
            response = ask([{"role": "user", "content": q["question"]}], system=HOOKS["system"], tools=claude_tools, model=MODEL_BALANCED, max_tokens=1024)
            asked = [(b.name, dict(b.input)) for b in response.content if b.type == "tool_use"]
            right = bool(asked) and all(n in names for n, _ in asked)
            rows.append({"label": q["label"], "stop_reason": response.stop_reason, "asked": [f"{n}({a})" for n, a in asked], "right": right})
            print(f"[{q['label']}] stop_reason: {response.stop_reason:<9} Claude asked for: {[f'{n}({a})' for n, a in asked] or 'nothing'}")
    right = sum(r["right"] for r in rows)
    score = f"{right}/{len(rows)} questions made Claude ask for a server tool (nothing was forwarded)"
    print(f"\nRESULT: {score}. Claude chose these tools from the descriptions the server wrote.")
    return {"rows": rows, "tool_names": sorted(names), "score": score}


# ---------------------------------------------------------------- stage 3: the server answers
async def stage3():
    async with HOOKS["open_session"]("notes_server.py") as session:
        claude_tools = await converted_tools(session)
        rows = []
        for q in QUESTIONS:
            send, log = recorder()
            result = await HOOKS["answer"](session, claude_tools, q["question"], send=send)
            flagged = flagged_errors(log["messages"])
            ok = (grounded(result["answer"], q["facts"]) and bool(result["tools_used"])) if q["facts"] else (flagged >= 1 and not result.get("gave_up"))
            rows.append({"label": q["label"], "answer": result["answer"], "tools_used": result["tools_used"], "turns": result["turns"],
                         "flagged": flagged, "gave_up": bool(result.get("gave_up")), "ok": ok})
            print(f"[{q['label']}] server calls: {result['tools_used'] or 'none'}  turns: {result['turns']}  errors flagged: {flagged}  ok: {'yes' if ok else 'no '}")
            print(f"    answer: {short(result['answer'], 90)}")
    right = sum(r["ok"] for r in rows)
    score = f"{right}/{len(rows)} questions answered from the server (the unknown note counts when its error reached Claude)"
    print(f"\nRESULT: {score}")
    return {"rows": rows, "score": score}


# ---------------------------------------------------------------- stage 4: a newer server adds delete_note
def recorded_delete_request():
    """A recorded model (no API call): it asks for delete_note once, then answers. It stands for a hallucinated or injected request."""
    state = {"n": 0}

    def send(messages, **kwargs):
        state["n"] += 1
        if state["n"] == 1:
            block = SimpleNamespace(type="tool_use", id="toolu_1", name="delete_note", input={"note_id": "N-3"})
            return SimpleNamespace(content=[block], stop_reason="tool_use")
        return SimpleNamespace(content=[SimpleNamespace(type="text", text="Done.")], stop_reason="end_turn")
    return send


async def count_notes(session):
    found = await session.call_tool("search_notes", {"query": ""})  # an empty query matches every note
    return len(json.loads(found.content[0].text))


async def stage4():
    async with HOOKS["open_session"]("notes_server_plus.py") as session:
        claude_tools = await converted_tools(session)
        offered = HOOKS["offer"](claude_tools)
        server_names, offered_names = sorted(t["name"] for t in claude_tools), sorted(t["name"] for t in offered)
        print(f"the newer server offers {len(server_names)} tools: {server_names}")
        print(f"your client hands Claude {len(offered_names)} of them: {offered_names}")
        before = await count_notes(session)
        print(f"\nrecorded model (no API call) now asks for delete_note('N-3'); notes on the server before: {before}")
        send, log = recorder(recorded_delete_request())
        result = await HOOKS["answer"](session, offered, "Please clean up the old release checklist note.", send=send)
        after = await count_notes(session)
        flagged = flagged_errors(log["messages"])
        print(f"tool_result flagged is_error: {flagged}  notes on the server after: {after}")
    refused = after == before
    score = f"Claude offered {len(offered_names)} of {len(server_names)} tools, delete_note {'REFUSED' if refused else 'FORWARDED and a note was DELETED'} (notes {before} -> {after})"
    print(f"\nRESULT: {score}")
    return {"server_tools": server_names, "offered_tools": offered_names, "notes_before": before, "notes_after": after,
            "flagged": flagged, "tools_used": result["tools_used"], "score": score}


def run_stage(stage):
    import asyncio
    hr(f"STAGE {stage} - {STAGE_TITLES[stage]}")
    print(f"model: {MODEL_BALANCED}  (stage 1 and the recorded part of stage 4 make no model call)\n")
    try:
        data = asyncio.run({1: stage1, 2: stage2, 3: stage3, 4: stage4}[stage]())
    except NotImplementedError as stub:
        raise SystemExit(f"{stub}. Paste the snippet from the guide, then run stage {stage} again.")
    save(f"stage{stage}.json", {"stage": stage, **data})
    history(stage)
