"""Plumbing for Lab 2.3 (payroll typed errors). Taken from the same harness as Demo 2B. You do not edit this file.

It runs the payroll agent on six tickets (data/scenarios.json) against the mock payroll database, and changes what the HARNESS does
at each stage, using the pieces you write in lab.py:

  stage 1  the raw loop: the model sees a bare error string, and the harness retries every failure blindly
  stage 2  + your typed errors (ERROR_CATALOG, to_tool_result); one attempt per call, no harness retry
  stage 3  + your retry table (RETRY_POLICY, policy_for); bounded retry with backoff, repeat calls blocked
  stage 4  + your approval request; permission errors are escalated to a human, never retried
  stage 5  + your preflight; every request is checked before it is sent, and four broken conversations are replayed
"""
import json
import pathlib
from dataclasses import dataclass, field

from claude_client import MODEL_BALANCED, ask, text_of, tool_calls_of
from payroll_db import PayrollDB, PayrollError, SimClock

HERE = pathlib.Path(__file__).parent
EVIDENCE = HERE / "evidence"
RUNAWAY_CAP = 12  # safety net so the raw loop ends; a correct policy never needs it
HOOKS = {"to_tool_result": None, "policy_for": None, "build_approval_request": None, "preflight": None}
STAGE_TITLES = {1: "raw loop: bare errors, blind retry", 2: "typed errors, one attempt", 3: "bounded retry with backoff",
                4: "permission errors escalated", 5: "preflight before every request"}


def configure(**pieces):
    HOOKS.update(pieces)


# ---------------------------------------------------------------- tools and prompts (given)
def _schema(props, required):
    return {"type": "object", "properties": props, "required": required, "additionalProperties": False}


S = {"type": "string"}
TOOL_SCHEMAS = [
    {"name": "lookup_employee",
     "description": "Look up one employee by id (format E####). Returns name, department and status. Read-only and safe to repeat.",
     "input_schema": _schema({"employee_id": S}, ["employee_id"])},
    {"name": "check_pay_period",
     "description": "Return the status (open|closed) of a pay period (YYYY-MM) and the next open period that can still accept adjustments. Read-only.",
     "input_schema": _schema({"period": S}, ["period"])},
    {"name": "apply_adjustment",
     "description": ("Apply a one-off pay adjustment (positive = pay, negative = deduction) to an employee for an open pay period. "
                     "Writes to the payroll ledger. Safe to retry ONLY with the same idempotency_key. "
                     "Errors come back with an error_code and, when typed, category, retryable and hint."),
     "input_schema": _schema({"employee_id": S, "period": S, "amount_cents": {"type": "integer"}, "reason": S, "idempotency_key": S},
                             ["employee_id", "period", "amount_cents", "reason", "idempotency_key"])},
]

SYSTEM = """You are the payroll adjustment agent. Apply the requested adjustment with the tools.
Tool failures arrive as is_error tool_results. When they contain JSON with error_code, category, retryable and hint, follow the hint.
Never repeat a call whose error says retryable=false, and never work around an approval requirement.
Use the ticket key as idempotency_key and convert dollars to cents. When done, reply with ONE JSON object and nothing else:
{"status": "applied|offer_next_period|needs_input|escalated|failed_transient|failed", "summary": "<one sentence>",
 "next_period": "<YYYY-MM or null>", "approval_request_id": "<id or null>"}"""


@dataclass(frozen=True)
class RetryPolicy:
    """max_attempts counts the first try. Wait before retry k (k = attempts so far, from 1)
    is min(base_delay_s * factor ** (k - 1), max_delay_s)."""
    max_attempts: int = 1
    base_delay_s: float = 0.0
    factor: float = 2.0
    max_delay_s: float = 0.0


def delay_before_retry(policy, attempts_made):
    return min(policy.base_delay_s * policy.factor ** (attempts_made - 1), policy.max_delay_s)


@dataclass
class RunContext:
    """Per-scenario recorder."""
    scenario_id: str
    trace: list = field(default_factory=list)  # one entry per attempt that reached the DB
    results: list = field(default_factory=list)  # what the model saw
    escalations: list = field(default_factory=list)
    final_failures: dict = field(default_factory=dict)  # canonical call -> final error content
    runaway: bool = False


# ---------------------------------------------------------------- the harness
def bare_error(exc):
    """What the raw loop shows the model: a string, nothing to branch on."""
    return f"Error: {exc.message}"


def run_tool(db, name, args, stage):
    """Run one tool call on the mock DB. Never raises. Returns (content, is_error, exception or None)."""
    handlers = {"lookup_employee": db.lookup_employee, "check_pay_period": db.check_pay_period, "apply_adjustment": db.apply_adjustment}
    render = HOOKS["to_tool_result"] if stage >= 2 else (lambda e, **_: bare_error(e))
    try:
        if name not in handlers:
            raise PayrollError(f"Unknown tool {name}")
        return json.dumps(handlers[name](**args), sort_keys=True), False, None
    except PayrollError as exc:
        return render(exc), True, exc
    except TypeError as exc:  # the model sent bad arguments
        wrapped = PayrollError(f"Invalid arguments for {name}: {exc}")
        return render(wrapped), True, wrapped


def canonical(name, args):
    return name + json.dumps(args, sort_keys=True)


def blocked_copy(content):
    try:
        body = json.loads(content)
        body.setdefault("details", {})["repeat_blocked"] = True
        body["retryable"] = False
        return json.dumps(body, sort_keys=True)
    except ValueError:
        return content


def execute_with_policy(db, clock, name, args, ctx, stage=5):
    """Run one tool call the way the stage says. Returns (tool_result content, is_error)."""
    key = canonical(name, args)
    if stage >= 3 and key in ctx.final_failures:  # the same call already failed for good: do not touch the DB again
        return blocked_copy(ctx.final_failures[key]), True
    attempt = 0
    while True:
        attempt += 1
        content, is_error, exc = run_tool(db, name, args, stage)
        ctx.trace.append({"tool": name, "attempt": attempt, "kind": "db", "error_code": exc.code if exc else None})
        if not is_error:
            return content, False
        if stage == 1:  # the raw loop treats every error as maybe-transient
            if attempt >= RUNAWAY_CAP:
                ctx.runaway = True
                return content, True
            clock.sleep(1.0)
            continue
        if stage == 2:
            return content, True
        if stage >= 4 and exc.code == "HR_APPROVAL_REQUIRED":
            request = HOOKS["build_approval_request"](name, args, exc)
            ctx.escalations.append(request)
            content = HOOKS["to_tool_result"](exc, extra={"approval_request_id": request.get("request_id")})
            ctx.final_failures[key] = content
            return content, True
        policy = HOOKS["policy_for"](exc.code)
        if attempt < policy.max_attempts and attempt < RUNAWAY_CAP:
            clock.sleep(delay_before_retry(policy, attempt))
            continue
        if attempt > 1:  # a retry budget was spent
            content = HOOKS["to_tool_result"](exc, extra={"attempts": attempt, "retries_exhausted": True}, retryable=False,
                                              hint="Retries are exhausted. Do not call this tool again. Tell the requester the payroll system is unavailable and stop.")
        ctx.final_failures[key] = content
        return content, True


# ---------------------------------------------------------------- the agent loop
def request_text(sc):
    return (f"Payroll ticket {sc['key']}: apply a ${sc['amount']} adjustment ({sc['reason']}) "
            f"to employee {sc['employee_id']} for pay period {sc['period']}.")


def run_agent(db, clock, ctx, user_text, stage, max_turns=8):
    """Standard manual tool loop: call Claude, run each tool_use through execute_with_policy, send ALL results back in ONE user message."""
    messages = [{"role": "user", "content": user_text}]
    for turn in range(1, max_turns + 1):
        if stage >= 5:
            problems = HOOKS["preflight"](messages)
            if problems:
                raise RuntimeError("preflight refused to send: " + "; ".join(problems))
        response = ask(messages, system=SYSTEM, tools=TOOL_SCHEMAS, model=MODEL_BALANCED, max_tokens=2048)
        calls = tool_calls_of(response)
        if response.stop_reason != "tool_use" or not calls:
            return {"turns": turn, "stopped": "end_turn", "final_text": text_of(response)}
        messages.append({"role": "assistant", "content": [b.model_dump(exclude_none=True) for b in response.content]})
        results = []
        for call in calls:
            content, is_error = execute_with_policy(db, clock, call.name, dict(call.input), ctx, stage)
            ctx.results.append({"tool": call.name, "is_error": is_error, "content": content})
            block = {"type": "tool_result", "tool_use_id": call.id, "content": content}
            if is_error:
                block["is_error"] = True
            results.append(block)
        messages.append({"role": "user", "content": results})
    return {"turns": max_turns, "stopped": "max_turns", "final_text": ""}


def parse_final(text):
    try:
        start, end = text.index("{"), text.rindex("}") + 1
        obj = json.loads(text[start:end])
        return obj if isinstance(obj, dict) else {}
    except ValueError:
        return {}


# ---------------------------------------------------------------- reporting
def hr(title):
    print(f"\n{'=' * 8} {title} {'=' * 8}")


def save(name, payload):
    EVIDENCE.mkdir(exist_ok=True)
    (EVIDENCE / name).write_text(json.dumps(payload, indent=1, default=str), encoding="utf-8")


def history(upto):
    print("\nPROGRESS ACROSS STAGES (six tickets)")
    print(f"{'stage':<7}{'what changed':<38}{'right':>6}{'db apply':>10}{'wait s':>8}{'escal':>7}{'runaway':>9}")
    for s in range(1, upto + 1):
        path = EVIDENCE / f"stage{s}.json"
        if not path.exists():
            print(f"{s:<7}{STAGE_TITLES[s]:<38}{'(run this stage first)':>30}")
            continue
        t = json.loads(path.read_text(encoding="utf-8"))["totals"]
        print(f"{s:<7}{STAGE_TITLES[s]:<38}{t['right']:>3}/{t['n']:<2}{t['apply_calls']:>10}{t['wait_s']:>8.1f}{t['escalations']:>7}{t['runaway']:>9}")


def replay_broken_conversations():
    """Stage 5: the four tool_result mistakes of Demo 2B stage 4, checked by YOUR preflight (no API call)."""
    cases = json.loads((HERE / "data" / "broken_conversations.json").read_text(encoding="utf-8"))
    print(f"\n{'case':<5}{'conversation':<40}{'preflight says'}")
    table = {}
    for case in cases:
        problems = HOOKS["preflight"](case["messages"])
        table[case["id"]] = problems
        verdict = f"CAUGHT: {problems[0]}" if problems else "ok, nothing to report"
        print(f"{case['id']:<5}{case['title']:<40}{verdict}")
    return {c["id"]: {"caught": bool(table[c["id"]]), "expect_caught": c["expect_caught"]} for c in cases}


def run_stage(stage, only=None):
    hr(f"STAGE {stage} - {STAGE_TITLES[stage]}")
    preflight_table = replay_broken_conversations() if stage == 5 else None
    scenarios = json.loads((HERE / "data" / "scenarios.json").read_text(encoding="utf-8"))
    clock = SimClock()
    db = PayrollDB(clock)
    print(f"model: {MODEL_BALANCED}\n")
    print(f"{'scn':<4}{'ticket':<34}{'db apply':>9}{'wait s':>8}  {'status':<18}{'expected':<18}esc")
    rows, extra_evidence = [], {}
    for sc in scenarios:
        if only and sc["id"] != only:
            continue
        db.arm_lock(sc["lock"])
        calls0, sleeps0 = len(db.calls), len(clock.sleeps)
        ctx = RunContext(sc["id"])
        run = run_agent(db, clock, ctx, request_text(sc), stage)
        final = parse_final(run["final_text"])
        status = final.get("status", "unparseable" if run["stopped"] == "end_turn" else "max_turns")
        db_calls = [list(c) for c in db.calls[calls0:]]
        sleeps = clock.sleeps[sleeps0:]
        apply_calls = sum(1 for op, _ in db_calls if op == "apply_adjustment")
        row = {"id": sc["id"], "title": sc["title"], "status": status, "expected_status": sc["expected_status"], "apply_calls": apply_calls,
               "wait_s": round(sum(sleeps), 2), "escalations": ctx.escalations, "runaway": ctx.runaway, "turns": run["turns"],
               "final": final, "trace": ctx.trace, "model_saw": [r["content"][:300] for r in ctx.results if r["is_error"]]}
        rows.append(row)
        print(f"{sc['id']:<4}{sc['title']:<34}{apply_calls:>9}{row['wait_s']:>8.1f}  {status:<18}{sc['expected_status']:<18}{len(ctx.escalations)}" + ("  RUNAWAY" if ctx.runaway else ""))
        db.arm_lock(0)
    totals = {"n": len(rows), "right": sum(r["status"] == r["expected_status"] for r in rows), "apply_calls": sum(r["apply_calls"] for r in rows),
              "wait_s": sum(r["wait_s"] for r in rows), "escalations": sum(len(r["escalations"]) for r in rows), "runaway": sum(r["runaway"] for r in rows)}
    rows_by_id = {r["id"]: r for r in rows}
    for sid in ("S2", "S4", "S6"):
        if sid in rows_by_id and rows_by_id[sid]["model_saw"]:
            print(f"\nwhat the model saw on {sid} ({rows_by_id[sid]['title']}):\n  {rows_by_id[sid]['model_saw'][-1]}")
    print(f"\nrows written to the ledger: {sorted(db.adjustments)}")
    save(f"stage{stage}.json", {"stage": stage, "rows": rows_by_id, "totals": totals, "ledger_keys": sorted(db.adjustments), "preflight": preflight_table})
    history(stage)
    if stage == 5 and not only:
        bar = totals["right"] >= 5 and not totals["runaway"]
        caught_ok = all(v["caught"] == v["expect_caught"] for v in preflight_table.values()) if preflight_table else False
        print(f"\nGATE: {totals['right']}/6 tickets right, runaways {totals['runaway']}, preflight table {'correct' if caught_ok else 'WRONG'} -> "
              + ("PASS" if bar and caught_ok else "FAIL"))
