"""Plumbing for Lab 2.1 (facilities tool boundaries). Taken from the same harness as Demo 2A. You do not edit this file.

It builds the tool set of each stage from the pieces you write in lab.py, sends the SAME 16 prompts to the real models with
tool_choice AUTO, grades the CAPABILITY that the chosen tool reaches, and prints what moved.

  stage 1  the legacy 11 tools                      (nothing of yours is used)
  stage 2  the same 11 tools, your DESCRIPTIONS
  stage 3  + your CONSOLIDATED tools (added next to the old ones, so the model sees 13)
  stage 4  - your REMOVE list (the old duplicates go)
  stage 5  + your SCOPES (each desk sees only its own tools)
"""
import copy
import json
import pathlib
from collections import Counter
from concurrent.futures import ThreadPoolExecutor

import toolset_original as legacy
from claude_client import MODEL_BALANCED, MODEL_FAST, cost_usd
from toolset_lint import lint

HERE = pathlib.Path(__file__).parent
EVIDENCE = HERE / "evidence"
CALLS = []
HOOKS = {"ask_with_tools": None, "descriptions": {}, "consolidated": [], "consolidated_map": {}, "remove": [], "scopes": {}}
S = {"type": "string"}
STAGE_TITLES = {1: "the legacy 11 tools", 2: "descriptions rewritten", 3: "consolidated tools added (old ones still offered)",
                4: "old duplicates removed", 5: "scoped per desk"}
SYSTEM = ("You are the facilities assistant for a corporate campus. For each request pick the one tool that fits "
          "best and call it with sensible arguments. Do not answer from memory when a tool applies.")
MODELS = {"fast": MODEL_FAST, "balanced": MODEL_BALANCED}


def configure(**pieces):
    HOOKS.update(pieces)


def tool(name, description, properties, required=None):
    """A tool definition in the Messages API shape: name, description, input_schema."""
    return {"name": name, "description": description,
            "input_schema": {"type": "object", "properties": properties, "required": required or [], "additionalProperties": False}}


def load_prompts():
    lines = (HERE / "data" / "eval_prompts.jsonl").read_text(encoding="utf-8").splitlines()
    return [json.loads(line) for line in lines if line.strip()]


# ================================================================ the tool set of each stage
def build_stage(stage):
    """-> (tools, capability_map, scopes) for a stage, from the legacy tools and the student's pieces."""
    tools = copy.deepcopy(legacy.LEGACY_TOOLS)
    cap_map = dict(legacy.LEGACY_MAP)
    if stage >= 2:
        for t in tools:
            if t["name"] in HOOKS["descriptions"]:
                t["description"] = HOOKS["descriptions"][t["name"]]
    if stage >= 3:
        tools += copy.deepcopy(HOOKS["consolidated"])
        cap_map.update(HOOKS["consolidated_map"])
    if stage >= 4:
        removed = set(HOOKS["remove"])
        tools = [t for t in tools if t["name"] not in removed]
        cap_map = {route: cap for route, cap in cap_map.items() if route.partition(":")[0] not in removed}
    everything = {context: [t["name"] for t in tools] for context in legacy.CONTEXTS}
    scopes = HOOKS["scopes"] if stage >= 5 and HOOKS["scopes"] else everything
    return tools, cap_map, scopes


# ================================================================ the eval (the same in every stage)
def capability_reached(cap_map, tool_name, tool_input):
    """Which real capability did this call reach? Tools with an `action` enum map as "tool:action"."""
    action = (tool_input or {}).get("action")
    if action and f"{tool_name}:{action}" in cap_map:
        return cap_map[f"{tool_name}:{action}"]
    return cap_map.get(tool_name)


def reachable(cap_map, scope):
    return {capability for route, capability in cap_map.items() if route.partition(":")[0] in scope}


def ask_one(model, tools, prompt, label):
    """One request: the Claude call itself is your TODO 1. Returns the tool_use blocks of the answer."""
    response = HOOKS["ask_with_tools"](model, tools, prompt)
    CALLS.append({"label": label, "model": model, "cost": cost_usd(response)})
    return [b for b in response.content if getattr(b, "type", None) == "tool_use"]


def evaluate(model, prompts, tools, cap_map, scopes, label):
    by_name = {t["name"]: t for t in tools}

    def run(prompt):
        scope = scopes[prompt["context"]]
        offered = [{k: by_name[n][k] for k in ("name", "description", "input_schema")} for n in scope if n in by_name]
        calls = ask_one(model, offered, prompt["prompt"], f"{label}:{prompt['id']}")
        name = calls[0].name if calls else None
        args = dict(calls[0].input) if calls else {}
        capability = capability_reached(cap_map, name, args) if name else None
        return {"id": prompt["id"], "expected": prompt["correct"], "got_tool": name, "got_action": args.get("action"),
                "got_capability": capability, "correct": capability in prompt["correct"],
                "scope_miss": not (set(prompt["correct"]) & reachable(cap_map, scope)), "offered": len(offered),
                "def_tokens": len(json.dumps(offered)) // 4}

    with ThreadPoolExecutor(max_workers=6) as pool:
        rows = list(pool.map(run, prompts))
    confusions = Counter((r["expected"][0], (r["got_tool"] or "(no tool)") + (f":{r['got_action']}" if r["got_action"] else ""))
                         for r in rows if not r["correct"])
    return {"correct": sum(r["correct"] for r in rows), "total": len(rows), "score_pct": round(100.0 * sum(r["correct"] for r in rows) / len(rows), 1),
            "per_prompt": rows, "confusions": [[e, g, n] for (e, g), n in confusions.most_common()],
            "scope_misses": [r["id"] for r in rows if r["scope_miss"]], "tools_offered": round(sum(r["offered"] for r in rows) / len(rows), 1),
            "def_tokens": round(sum(r["def_tokens"] for r in rows) / len(rows))}


def hr(title):
    print(f"\n{'=' * 8} {title} {'=' * 8}")


def print_ledger():
    total = sum(c["cost"] for c in CALLS)
    print(f"\n[ledger] {len(CALLS)} Claude calls; estimated cost ${total:.4f}")


def lint_summary(tools, cap_map, scopes):
    rows = lint(tools, cap_map, scopes)
    failed = [name for name, ok, _ in rows if not ok]
    return {"passed": len(rows) - len(failed), "total": len(rows), "failed": failed, "rows": rows}


def save(name, payload):
    EVIDENCE.mkdir(exist_ok=True)
    (EVIDENCE / name).write_text(json.dumps(payload, indent=1, default=str), encoding="utf-8")


def history(upto):
    print("\nPROGRESS ACROSS STAGES (score on the 16 prompts; tools offered; definition tokens; lint checks passed)")
    print(f"{'stage':<7}{'what changed':<50}{'fast':>7}{'balanced':>10}{'tools':>7}{'def tok':>9}{'lint':>7}")
    for s in range(1, upto + 1):
        path = EVIDENCE / f"stage{s}.json"
        if not path.exists():
            print(f"{s:<7}{STAGE_TITLES[s]:<50}{'(run this stage first)':>26}")
            continue
        d = json.loads(path.read_text(encoding="utf-8"))
        m = d["models"]
        cell = lambda a: f"{m[a]['score_pct']:.0f}%" if a in m else "n/a"  # noqa: E731
        ref = m.get("balanced") or m.get("fast")
        print(f"{s:<7}{STAGE_TITLES[s]:<50}{cell('fast'):>7}{cell('balanced'):>10}{ref['tools_offered']:>7}{ref['def_tokens']:>9}{d['lint']['passed']:>4}/{d['lint']['total']}")


# ================================================================ the stages
def run_stage(stage, models):
    hr(f"STAGE {stage} - {STAGE_TITLES[stage]}")
    tools, cap_map, scopes = build_stage(stage)
    prompts = load_prompts()
    print(f"{len(tools)} tools: {', '.join(t['name'] for t in tools)}")
    if stage == 5:
        for context, names in scopes.items():
            print(f"  desk {context:<18} {len(names):>2} tools: {', '.join(names)}")
    results = {alias: evaluate(MODELS[alias], prompts, tools, cap_map, scopes, f"s{stage}:{alias}") for alias in models}
    lint_rows = lint_summary(tools, cap_map, scopes)
    print(f"\n{'id':<5}{'expected':<18}" + "".join(f"{a + ' picked':<30}" for a in results))
    first = next(iter(results.values()))
    for k, row in enumerate(first["per_prompt"]):
        line = f"{row['id']:<5}{row['expected'][0]:<18}"
        for alias, r in results.items():
            x = r["per_prompt"][k]
            picked = (x["got_tool"] or "(no tool)") + (f":{x['got_action']}" if x["got_action"] else "")
            line += f"{picked:<26}{'ok' if x['correct'] else 'X':<4}"
        print(line)
    for alias, r in results.items():
        print(f"\n[{alias}] {r['correct']}/{r['total']} = {r['score_pct']}%   tools offered {r['tools_offered']}   definition tokens/request about {r['def_tokens']}")
        for expected, got, n in r["confusions"][:5]:
            print(f"    {n}x  expected {expected:<17} -> picked {got}")
        if r["scope_misses"]:
            print(f"    SCOPE MISS (the right tool was not offered in that context): {r['scope_misses']}")
    print(f"\ntoolset lint: {lint_rows['passed']}/{lint_rows['total']} checks pass" + (f"; failing: {', '.join(lint_rows['failed'])}" if lint_rows["failed"] else ""))
    if stage == 5 or stage == 1:
        for name, ok, detail in lint_rows["rows"]:
            print(f"  [{'ok' if ok else '!!'}] {name}: {detail}")
    save(f"stage{stage}.json", {"stage": stage, "models": results, "lint": {k: lint_rows[k] for k in ("passed", "total", "failed")},
                              "tool_names": [t["name"] for t in tools]})
    history(stage)


BAR = {"balanced": 85.0, "fast": 75.0}


def stage_gate(models):
    """The CI-style gate: the final toolset must pass the lint and the score bar, and a sprawl regression must be caught."""
    hr("GATE - the final toolset against the bar")
    tools, cap_map, scopes = build_stage(5)
    results = {alias: evaluate(MODELS[alias], load_prompts(), tools, cap_map, scopes, f"gate:{alias}") for alias in models}
    lint_rows = lint_summary(tools, cap_map, scopes)
    problems = []
    for alias, r in results.items():
        print(f"[{alias}] {r['score_pct']}% (bar {BAR[alias]}%)   scope misses: {r['scope_misses'] or 'none'}")
        if r["score_pct"] < BAR[alias]:
            problems.append(f"{alias} {r['score_pct']}% is below the bar {BAR[alias]}%")
        if r["scope_misses"]:
            problems.append(f"{alias}: scope misses {r['scope_misses']}")
    problems += [f"lint: {name}" for name in lint_rows["failed"]]
    hr("a teammate re-adds three legacy tools: does the lint catch it? (no model call)")
    sprawl = copy.deepcopy(tools) + [t for t in legacy.LEGACY_TOOLS if t["name"] in ("find_room", "reserve_slot", "ticket_open")]
    sprawl_map = {**cap_map, "find_room": "room.get", "reserve_slot": "room.hold", "ticket_open": "ticket.list_open"}
    sprawl_lint = lint_summary(sprawl, sprawl_map, {c: [t["name"] for t in sprawl] for c in legacy.CONTEXTS})
    print(f"lint after the change: {sprawl_lint['passed']}/{sprawl_lint['total']} pass; failing: {', '.join(sprawl_lint['failed'])}")
    for p in problems:
        print(f"[GATE-FAIL] {p}")
    print("GATE " + ("PASS" if not problems else "FAIL"))
    save("gate.json", {"pass": not problems, "problems": problems, "scores": {a: r["score_pct"] for a, r in results.items()},
                       "sprawl_failed": sprawl_lint["failed"], "lint": lint_rows["failed"]})
