"""Plumbing for Demo 1C and Lab 1C (the structured-output failure lab). In the lab you do not edit this file.

The story: a JSON schema guarantees the SHAPE of an invoice record, not the MONEY in it. This file holds the
schema, the given validators, the retry loop, the review queue and the five stages. Four pieces are supplied from
outside through configure(): ask_extraction, arithmetic_issues, grounding_issues and decide.
"""
import json
import pathlib
import re
from dataclasses import dataclass, asdict
from datetime import date
from decimal import Decimal, ROUND_HALF_UP, InvalidOperation

from claude_client import MODEL_BALANCED, MODEL_FAST, cost_usd, text_of

HERE = pathlib.Path(__file__).parent
DATA = HERE / "data"
EVIDENCE = HERE / "evidence"
CALLS = []
HOOKS = {}  # filled by demo.py / lab.py: ask_extraction, arithmetic_issues, grounding_issues, decide
LAB_DOCS = ["inv_001", "inv_002", "inv_003", "inv_004", "inv_006", "inv_007", "inv_009", "inv_010"]
START_MAX_TOKENS = 400   # small on purpose: the 12-line invoice (inv_010) cannot finish in 400 tokens
MAX_TOKENS_CAP = 4096
MAX_ATTEMPTS = 3
TOLERANCE = Decimal("0.02")  # rounding allowance for amounts derived from a rate
ACCEPT, RETRY_CORRECT, RETRY_LARGER, REVIEW = "accept", "retry_correct", "retry_larger_max_tokens", "review"


def configure(**hooks):
    HOOKS.update(hooks)


# ================================================================ data
def load_docs(only=None):
    docs = [json.loads(line) for line in (DATA / "invoices.jsonl").read_text(encoding="utf-8").splitlines() if line.strip()]
    return [d for d in docs if only is None or d["doc_id"] in only]


def load_truth():
    return json.loads((DATA / "ground_truth.json").read_text(encoding="utf-8"))


def load_vendors():
    return json.loads((DATA / "vendor_config.json").read_text(encoding="utf-8"))["vendors"]


def load_fixtures():
    return json.loads((DATA / "known_bad_outputs.json").read_text(encoding="utf-8"))["fixtures"]


def D(x):
    return Decimal(str(x))


def money(x):
    return D(x).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)


@dataclass
class Issue:
    path: str
    kind: str      # structural | semantic | grounding | parse
    message: str


def issue(path, kind, message):
    return Issue(path, kind, message)


def feedback(issues):
    return "\n".join(f"- {i.path}: {i.message}" for i in issues)


# ================================================================ the request (SYSTEM prompt, schema)
SYSTEM = (
    "You extract structured data from supplier invoices for an accounts-payable ledger.\n"
    "Rules:\n"
    "1. Copy every monetary figure and percentage exactly as it is printed in the document. "
    "Never compute, round, balance or adjust a figure to make the totals add up.\n"
    "2. Dates must be ISO 8601 (YYYY-MM-DD). Currency must be a 3-letter ISO 4217 code.\n"
    "3. Numbers in European format (1.234,56) mean 1234.56.\n"
    "4. If a printed value is illegible or two printed values contradict each other, copy the value you can read "
    "and describe the problem in extraction_notes. Use an empty string for extraction_notes when there is no problem.\n"
    "5. line_items is an empty array when the document has no itemised lines."
)
_MONEY = {"type": "number"}
INVOICE_SCHEMA = {
    "type": "object",
    "properties": {
        "invoice_number": {"type": "string"},
        "vendor_name": {"type": "string"},
        "invoice_date": {"type": "string"},
        "due_date": {"type": "string"},
        "currency": {"type": "string"},
        "line_items": {"type": "array", "items": {"type": "object", "properties": {
            "description": {"type": "string"}, "quantity": {"type": "number"}, "unit_price": _MONEY, "amount": _MONEY},
            "required": ["description", "quantity", "unit_price", "amount"], "additionalProperties": False}},
        "subtotal": _MONEY,
        "tax_rate_percent": {"anyOf": [{"type": "number"}, {"type": "null"}]},
        "tax_amount": _MONEY,
        "total": _MONEY,
        "extraction_notes": {"type": "string"},
    },
    "required": ["invoice_number", "vendor_name", "invoice_date", "due_date", "currency", "line_items",
                 "subtotal", "tax_rate_percent", "tax_amount", "total", "extraction_notes"],
    "additionalProperties": False,
}
OUTPUT_FORMAT = {"type": "json_schema", "schema": INVOICE_SCHEMA}


def user_message(source_text):
    return f"<document>\n{source_text}\n</document>\n\nExtract the invoice into the required JSON structure."


RULES = (
    "Correction rules:\n"
    "- The document is the source of truth. Printed figures are authoritative; do not change a figure that is "
    "printed in the document in order to satisfy an arithmetic check.\n"
    "- If the failure comes from a figure you misread, fix that figure to what the document prints.\n"
    "- If the document itself is inconsistent or illegible, keep the printed values and explain the problem in "
    "extraction_notes instead of inventing numbers.\n"
    "- Change only the fields named in the failures unless another field is demonstrably misread."
)


def correction_message(source_text, previous_text, issues, round_no, max_rounds, naive=False):
    """The retry prompt: original request + the invalid output + the specific failures (+ which number is authoritative)."""
    if naive:
        return (user_message(source_text) + "\n\nYour previous answer was:\n" + previous_text
                + "\n\nIt failed validation:\n" + feedback(issues) + "\n\nReturn the corrected JSON.")
    try:
        previous_text = json.dumps(json.loads(previous_text), indent=1)
    except ValueError:
        pass
    return (user_message(source_text) + "\n\n<previous_output>\n" + previous_text + "\n</previous_output>"
            + "\n\n<validation_failures>\n" + feedback(issues) + "\n</validation_failures>\n\n" + RULES
            + f"\n\n[correction round {round_no} of at most {max_rounds}]")


# ================================================================ the Claude call (your TODO 1 in the lab) and its bookkeeping
def call_model(model, user, max_tokens, label=""):
    response = HOOKS["ask_extraction"](model, user, max_tokens)
    CALLS.append({"label": label, "model": model, "in": response.usage.input_tokens, "out": response.usage.output_tokens,
                  "stop": response.stop_reason, "cost": cost_usd(response)})
    return response


def print_ledger():
    total = sum(c["cost"] for c in CALLS)
    by_model = {}
    for c in CALLS:
        by_model[c["model"]] = by_model.get(c["model"], 0) + 1
    print(f"\n[ledger] {len(CALLS)} Claude calls ({', '.join(f'{n} x {m}' for m, n in by_model.items())}); estimated cost ${total:.4f}")


def parse_record(text):
    cleaned = re.sub(r"^```(?:json)?\s*|\s*```$", "", text.strip())
    record = json.loads(cleaned)
    if not isinstance(record, dict):
        raise ValueError("top-level JSON must be an object")
    return record


def classify(response):
    """Branch on stop_reason BEFORE reading the content. Returns (status, record, raw_text, parse_issues)."""
    text = text_of(response)
    if response.stop_reason == "refusal":
        return "refusal", None, text, []
    if response.stop_reason == "max_tokens":
        return "truncated", None, text, []
    try:
        return "ok", parse_record(text), text, []
    except ValueError as exc:
        return "unparseable", None, text, [issue("$", "parse", f"not valid JSON: {exc}")]


# ================================================================ validators: structural (schema), given semantic rules, grounding helpers
_DATE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def structural_issues(rec):
    """What the old intake checked: field names and JSON types. A local stand-in for JSON Schema validation."""
    problems = []
    props = INVOICE_SCHEMA["properties"]
    for key in INVOICE_SCHEMA["required"]:
        if key not in rec:
            problems.append(issue(key, "structural", "missing required field"))
    for key in rec:
        if key not in props:
            problems.append(issue(key, "structural", "unexpected field"))
    for key in ("invoice_number", "vendor_name", "invoice_date", "due_date", "currency", "extraction_notes"):
        if key in rec and not isinstance(rec[key], str):
            problems.append(issue(key, "structural", "must be a string"))
    for key in ("subtotal", "tax_amount", "total"):
        if key in rec and (isinstance(rec[key], bool) or not isinstance(rec[key], (int, float))):
            problems.append(issue(key, "structural", "must be a number"))
    if "tax_rate_percent" in rec and rec["tax_rate_percent"] is not None and not isinstance(rec["tax_rate_percent"], (int, float)):
        problems.append(issue("tax_rate_percent", "structural", "must be a number or null"))
    if "line_items" in rec and not isinstance(rec["line_items"], list):
        problems.append(issue("line_items", "structural", "must be an array"))
    for key in ("invoice_date", "due_date"):
        if isinstance(rec.get(key), str) and not _DATE.match(rec[key]):
            problems.append(issue(key, "structural", "must look like YYYY-MM-DD"))
    return problems


def _vendor(vendors, name):
    key = re.sub(r"\s+", " ", re.sub(r"[^a-z0-9& ]", " ", name.lower())).strip()
    for v in vendors:
        if any(re.sub(r"\s+", " ", re.sub(r"[^a-z0-9& ]", " ", n.lower())).strip() == key for n in v["names"]):
            return v
    return None


def tax_rate_issues(rec, vendors):
    vendor = _vendor(vendors, rec["vendor_name"])
    if vendor is None:
        return [issue("vendor_name", "semantic", f"vendor '{rec['vendor_name']}' is not in the vendor master")]
    allowed = [D(r) for r in vendor["allowed_tax_rates"]]
    subtotal, tax, rate = D(rec["subtotal"]), D(rec["tax_amount"]), rec["tax_rate_percent"]
    if rate is not None:
        if not any(abs(D(rate) - a) <= Decimal("0.01") for a in allowed):
            return [issue("tax_rate_percent", "semantic", f"{rate}% is not a rate vendor {vendor['vendor_id']} charges")]
        want = money(subtotal * D(rate) / 100)
        if abs(want - tax) > TOLERANCE:
            return [issue("tax_amount", "semantic", f"tax_amount {rec['tax_amount']} != {rate}% of subtotal {rec['subtotal']} = {want}")]
        return []
    if subtotal != 0 and not any(abs(tax / subtotal * 100 - a) <= Decimal("0.05") for a in allowed):
        return [issue("tax_amount", "semantic", f"tax_amount {rec['tax_amount']} on subtotal {rec['subtotal']} implies a rate vendor {vendor['vendor_id']} does not charge")]
    return []


def date_issues(rec):
    found = []
    parsed = {}
    for key in ("invoice_date", "due_date"):
        try:
            parsed[key] = date.fromisoformat(rec[key])
        except (ValueError, TypeError):
            found.append(issue(key, "semantic", f"{key} is not a valid calendar date"))
    if len(parsed) == 2 and parsed["due_date"] < parsed["invoice_date"]:
        found.append(issue("due_date", "semantic", f"due_date {rec['due_date']} is before invoice_date {rec['invoice_date']}"))
    return found


ISO_4217 = frozenset("AED AUD BRL CAD CHF CNY CZK DKK EUR GBP HKD HUF IDR ILS INR JPY KRW MXN MYR NOK NZD PHP PLN RON SAR SEK SGD THB TRY TWD USD ZAR".split())


def currency_issues(rec, vendors):
    if rec["currency"] not in ISO_4217:
        return [issue("currency", "semantic", f"'{rec['currency']}' is not an ISO 4217 currency code")]
    vendor = _vendor(vendors, rec["vendor_name"])
    if vendor and vendor["currency"] != rec["currency"]:
        return [issue("currency", "semantic", f"vendor {vendor['vendor_id']} bills in {vendor['currency']}, not {rec['currency']}")]
    return []


def line_item_issues(rec):
    items = rec["line_items"]
    if not items:
        return []
    found = []
    for i, it in enumerate(items):
        want = money(D(it["quantity"]) * D(it["unit_price"]))
        if abs(want - D(it["amount"])) > Decimal("0.01"):
            found.append(issue(f"line_items[{i}].amount", "semantic", f"line {i}: {it['quantity']} x {it['unit_price']} = {want}, not {it['amount']}"))
    lines_total = money(sum(D(it["amount"]) for it in items))
    if abs(lines_total - D(rec["subtotal"])) > Decimal("0.01"):
        found.append(issue("subtotal", "semantic", f"subtotal {rec['subtotal']} != sum of line_items amounts {lines_total}"))
    return found


def semantic_issues(rec, vendors):
    """All business rules. The arithmetic rule is the one YOU write in the lab (TODO 2)."""
    return (HOOKS["arithmetic_issues"](rec) + tax_rate_issues(rec, vendors) + date_issues(rec)
            + currency_issues(rec, vendors) + line_item_issues(rec))


# ---- grounding helpers (the per-field check is your TODO 3)
TOL = Decimal("0.005")
_TOKEN = re.compile(r"(?<![\w/\-.,])\d[\d.,]*\d(?![\w/\-])|(?<![\w/\-.,])\d(?![\w/\-.,])")


def _readings(tok):
    out = set()

    def add(text):
        try:
            out.add(Decimal(text))
        except InvalidOperation:
            pass

    if "." in tok and "," in tok:
        dec = "." if tok.rfind(".") > tok.rfind(",") else ","
        add(tok.replace("," if dec == "." else ".", "").replace(dec, "."))
    elif "," in tok:
        parts = tok.split(",")
        add(parts[0] + "." + parts[1] if len(parts) == 2 and len(parts[1]) in (1, 2) else tok.replace(",", ""))
    elif "." in tok:
        parts = tok.split(".")
        add(tok if len(parts) == 2 else "".join(parts))
        if len(parts) >= 2 and all(len(p) == 3 for p in parts[1:]):
            add("".join(parts))
    else:
        add(tok)
    return out


def extract_numbers(text):
    """Every number printed in the document, in every plausible reading (1.000,00 -> 1000)."""
    numbers = set()
    for match in _TOKEN.finditer(text):
        numbers |= _readings(match.group(0).rstrip(".,"))
    return numbers


def numeric_fields(rec):
    """(path, value) for every number in the record that should be printed in the document."""
    fields = [(name, D(rec[name])) for name in ("subtotal", "tax_amount", "total")]
    if rec.get("tax_rate_percent") is not None:
        fields.append(("tax_rate_percent", D(rec["tax_rate_percent"])))
    for i, item in enumerate(rec.get("line_items", [])):
        for name in ("quantity", "unit_price", "amount"):
            fields.append((f"line_items[{i}].{name}", D(item[name])))
    return fields


# ================================================================ comparison with ground truth (the audit; never shown to the model)
def diff_against_truth(record, entry):
    """Field names where `record` disagrees with ground truth. For documents that should go to review, ANY accepted record is a miss."""
    if entry["expect_review"]:
        return ["<should have gone to human review>"] if record is not None else []
    if record is None:
        return ["<no record>"]
    truth, wrong = entry["truth"], []
    for name in ("subtotal", "tax_amount", "total"):
        if abs(D(record[name]) - D(truth[name])) > Decimal("0.005"):
            wrong.append(name)
    for name in ("currency", "invoice_date", "due_date"):
        if record[name] != truth[name]:
            wrong.append(name)
    tr, rr = truth["tax_rate_percent"], record["tax_rate_percent"]
    if (tr is None) != (rr is None) or (tr is not None and abs(D(tr) - D(rr)) > Decimal("0.005")):
        wrong.append("tax_rate_percent")
    if len(record["line_items"]) != len(truth["line_items"]):
        wrong.append("line_items")
    return wrong


class Ledger:
    """Stand-in for the AP ledger. `post` is the point of no return: payments are scheduled from posted rows."""

    def __init__(self):
        self.rows = []

    def post(self, doc_id, record):
        self.rows.append({"doc_id": doc_id, "status": "posted", "record": record})

    def park(self, doc_id, record):
        self.rows.append({"doc_id": doc_id, "status": "parked", "record": record})

    def payable(self, currency):
        return sum((D(r["record"]["total"]) for r in self.rows if r["status"] == "posted" and r["record"]["currency"] == currency), Decimal(0))


def save(name, payload):
    EVIDENCE.mkdir(exist_ok=True)
    (EVIDENCE / name).write_text(json.dumps(payload, indent=1, default=str), encoding="utf-8")


def hr(title):
    print(f"\n{'=' * 8} {title} {'=' * 8}")


# ================================================================ the validate-and-retry loop (stages 4 and 5)
def collect_issues(rec, source_text, vendors, use_grounding):
    """Structural, then semantic, then grounding. Later layers run only when earlier ones pass."""
    found = structural_issues(rec)
    if found:
        return found
    found = semantic_issues(rec, vendors)
    if use_grounding:
        found += HOOKS["grounding_issues"](rec, source_text)
    return found


def extract_with_retries(doc, vendors, plan=(MODEL_BALANCED,), max_attempts=MAX_ATTEMPTS, use_grounding=True):
    """One document through the loop. `plan` is the model for each attempt (the last repeats).
    The loop never edits the model's output: it accepts it byte-for-byte or refuses it."""
    source, doc_id = doc["source_text"], doc["doc_id"]
    max_tokens, user, corrections, last_record, attempts = START_MAX_TOKENS, user_message(source), 0, None, []
    for number in range(1, max_attempts + 1):
        model = plan[min(number - 1, len(plan) - 1)]
        response = call_model(model, user, max_tokens, f"{doc_id}#{number}")
        status, record, raw, found = classify(response)
        if status == "ok":
            last_record = record
            found = found + collect_issues(record, source, vendors, use_grounding)
        action, reason = HOOKS["decide"](status, found, number, max_attempts, max_tokens, MAX_TOKENS_CAP)
        attempts.append({"attempt": number, "model": model, "status": status, "stop_reason": response.stop_reason,
                         "issues": [asdict(i) for i in found], "action": action, "reason": reason, "max_tokens": max_tokens,
                         "cost": cost_usd(response)})
        if action == ACCEPT:
            return {"doc_id": doc_id, "status": "accepted", "record": record, "last_record": last_record, "reason": reason, "attempts": attempts}
        if action == REVIEW:
            return {"doc_id": doc_id, "status": "needs_review", "record": None, "last_record": last_record, "reason": reason, "attempts": attempts}
        if action == RETRY_LARGER:
            max_tokens = min(max_tokens * 2, MAX_TOKENS_CAP)
        else:
            corrections += 1
            user = correction_message(source, raw, found, corrections, max_attempts - 1)
    raise AssertionError("decide() must return review on the last attempt")


def review_item(result, source_text):
    """What a human reviewer needs: why, the open issues, the last model output, the cost."""
    return {"doc_id": result["doc_id"], "needs_review": True, "reason": result["reason"], "attempts": len(result["attempts"]),
            "open_issues": result["attempts"][-1]["issues"], "last_model_output": result["last_record"],
            "source_excerpt": source_text[:300], "cost": round(sum(a["cost"] for a in result["attempts"]), 6)}


def metrics(results):
    n = len(results)
    accepted = [r for r in results if r["status"] == "accepted"]
    cost = sum(a["cost"] for r in results for a in r["attempts"])
    retried = [r for r in results if len(r["attempts"]) > 1]
    review = [r for r in results if r["status"] == "needs_review"]
    return {"documents": n, "accepted": len(accepted), "needs_review": len(review), "retried": len(retried),
            "retry_rate": round(len(retried) / n, 3), "fallback_rate": round(len(review) / n, 3),
            "total_attempts": sum(len(r["attempts"]) for r in results), "total_cost": round(cost, 6),
            "cost_per_accepted": round(cost / len(accepted), 6) if accepted else None}


def silent_corruptions(results, truth):
    return [(r["doc_id"], diff_against_truth(r["record"], truth[r["doc_id"]])) for r in results
            if r["status"] == "accepted" and diff_against_truth(r["record"], truth[r["doc_id"]])]


# ================================================================ STAGES
def _fixture_table(title, fixtures, checker):
    print(f"{title}\n{'fixture':<26}{'doc':<9}result")
    rows = []
    for f in fixtures:
        found = checker(f)
        rows.append({"name": f["name"], "doc_id": f["doc_id"], "issues": [i.message for i in found]})
        print(f"{f['name']:<26}{f['doc_id']:<9}" + ("passes (nothing found)" if not found else f"CAUGHT: {found[0].message[:70]}"))
    return rows


def stage1(docs, truth):
    """Schema passes, business wrong."""
    hr("A. recorded bad outputs through the schema check (no model call)")
    fixtures = load_fixtures()
    rows = _fixture_table("A schema-valid record can still be wrong about money:", fixtures, lambda f: structural_issues(f["record"]))
    for f in fixtures:
        wrong = diff_against_truth(f["record"], truth[f["doc_id"]])
        print(f"  {f['name']:<26} fields that disagree with the document: {', '.join(wrong) or 'none'}")
    hr(f"B. live extraction of {len(docs)} invoices, then straight into the ledger if the schema passes")
    ledger, table = Ledger(), []
    for d in docs:
        response = call_model(MODEL_BALANCED, user_message(d["source_text"]), 1024, d["doc_id"])
        status, record, raw, found = classify(response)
        if status != "ok":
            table.append({"doc_id": d["doc_id"], "posted": False, "note": f"stop_reason={response.stop_reason}", "wrong": []})
            print(f"{d['doc_id']:<9} not posted (stop_reason={response.stop_reason}: no policy yet)")
            continue
        found = structural_issues(record)
        wrong = diff_against_truth(record, truth[d["doc_id"]]) if not found else ["<schema>"]
        if not found:
            ledger.post(d["doc_id"], record)
        table.append({"doc_id": d["doc_id"], "posted": not found, "wrong": wrong})
        print(f"{d['doc_id']:<9} {'posted' if not found else 'rejected':<9} {'correct' if not wrong else 'WRONG: ' + ', '.join(wrong)}")
    posted = [t for t in table if t["posted"]]
    wrong_posted = [t for t in posted if t["wrong"]]
    print(f"\nposted to the ledger: {len(posted)}; posted but wrong: {len(wrong_posted)}")
    print("A good model may post every invoice correctly today. The schema is still not what made them correct.")
    save("stage1.json", {"fixtures": rows, "fixtures_schema_valid": all(not r["issues"] for r in rows), "live": table,
                         "posted": len(posted), "posted_wrong": len(wrong_posted)})


def stage2(docs, truth):
    """Semantic validators."""
    vendors = load_vendors()
    hr("A. recorded bad outputs through the business rules (no model call)")
    fixtures = load_fixtures()
    rows = _fixture_table("Which recorded failures do the rules catch?", fixtures, lambda f: semantic_issues(f["record"], vendors))
    caught = {r["name"]: bool(r["issues"]) for r in rows}
    print(f"\ncaught: {[n for n, c in caught.items() if c]}   missed: {[n for n, c in caught.items() if not c]}")
    hr(f"B. live extraction of {len(docs)} invoices, then the rules")
    table = []
    for d in docs:
        response = call_model(MODEL_BALANCED, user_message(d["source_text"]), 1024, d["doc_id"])
        status, record, raw, found = classify(response)
        if status != "ok":
            print(f"{d['doc_id']:<9} stop_reason={response.stop_reason} (skipped)")
            continue
        found = structural_issues(record) or semantic_issues(record, vendors)
        table.append({"doc_id": d["doc_id"], "issues": [i.message for i in found]})
        print(f"{d['doc_id']:<9} " + ("clean" if not found else f"{len(found)} issue(s): {found[0].message[:80]}"))
    save("stage2.json", {"fixtures": rows, "caught": caught, "live": table})


def stage3(docs, truth, naive=False):
    """Corrective retry (one retry, no grounding): the demo failure."""
    vendors = load_vendors()
    hr(f"live: extract, validate, retry ONCE with the {'naive' if naive else 'careful'} correction prompt (no grounding yet)")
    rows, corrupted = [], []
    for d in docs:
        first = call_model(MODEL_BALANCED, user_message(d["source_text"]), 1024, f"{d['doc_id']}#1")
        status, record, raw, found = classify(first)
        if status != "ok":
            print(f"{d['doc_id']:<9} stop_reason={first.stop_reason}: skipped (no policy yet)")
            rows.append({"doc_id": d["doc_id"], "outcome": "skipped", "wrong": []})
            continue
        found = structural_issues(record) or semantic_issues(record, vendors)
        final, retried = record, False
        if found:
            retried = True
            prompt = correction_message(d["source_text"], raw, found, 1, 1, naive=naive)
            status2, record2, raw2, found2 = classify(call_model(MODEL_BALANCED, prompt, 1024, f"{d['doc_id']}#2"))
            final = record2 if status2 == "ok" and not (structural_issues(record2) or semantic_issues(record2, vendors)) else None
        wrong = diff_against_truth(final, truth[d["doc_id"]]) if final else []
        outcome = "rejected" if final is None else ("accepted, WRONG: " + ", ".join(wrong) if wrong else "accepted, correct")
        if final is not None and wrong:
            corrupted.append(d["doc_id"])
        rows.append({"doc_id": d["doc_id"], "retried": retried, "outcome": outcome, "wrong": wrong})
        print(f"{d['doc_id']:<9} {'retried ' if retried else 'clean   '} {outcome}")
    hr("replay: the failure that matters (recorded output, no model call)")
    fixture = next(f for f in load_fixtures() if f["name"] == "silent_subtotal_edit")
    print("inv_002 prints subtotal 100.00, tax 18.00, total 118.00. A model told 'total != subtotal + tax' rewrote the wrong numbers:")
    for name in ("subtotal", "tax_amount", "total"):
        print(f"  {name:<12} {fixture['record'][name]}")
    print(f"  business rules on this record: {[i.message for i in semantic_issues(fixture['record'], vendors)] or 'ALL PASS'}")
    print(f"\naccepted records that disagree with the document (live run): {len(corrupted)} {corrupted or ''}")
    save("stage3.json", {"prompt": "naive" if naive else "careful", "live": rows, "live_corrupted": corrupted,
                         "fixture_passes_rules": not semantic_issues(fixture["record"], vendors)})


def stage4(docs, truth):
    """Grounding and the bounded loop."""
    vendors = load_vendors()
    hr("A. recorded bad outputs through the grounding check (no model call)")
    fixtures = load_fixtures()
    sources = {d["doc_id"]: d["source_text"] for d in load_docs()}
    rows = _fixture_table("Numbers that are not printed in the document:", fixtures,
                          lambda f: HOOKS["grounding_issues"](f["record"], sources[f["doc_id"]]))
    caught = {r["name"]: bool(r["issues"]) for r in rows}
    hr(f"B. live: the bounded loop (max {MAX_ATTEMPTS} attempts, start max_tokens {START_MAX_TOKENS}) on {len(docs)} invoices")
    results = []
    for d in docs:
        result = extract_with_retries(d, vendors, use_grounding=True)
        results.append(result)
        trail = " -> ".join(f"{a['status']}/{a['action']}" for a in result["attempts"])
        print(f"{d['doc_id']:<9} {result['status']:<13} {len(result['attempts'])} attempt(s): {trail}")
    bad = silent_corruptions(results, truth)
    m = metrics(results)
    print(f"\naccepted {m['accepted']}/{m['documents']}, sent to review {m['needs_review']}; silent corruptions: {len(bad)} {bad or ''}")
    save("stage4.json", {"fixtures": rows, "caught": caught, "metrics": m, "silent_corruptions": [b[0] for b in bad],
                         "results": [{"doc_id": r["doc_id"], "status": r["status"], "attempts": [{k: a[k] for k in ("model", "status", "action", "max_tokens")} for a in r["attempts"]]} for r in results]})


def stage5(docs, truth):
    """Review queue, metrics and the cheap-first cascade."""
    vendors = load_vendors()
    summary = {}
    for name, plan in (("balanced only", (MODEL_BALANCED,)), ("cheap first (haiku, haiku, sonnet)", (MODEL_FAST, MODEL_FAST, MODEL_BALANCED))):
        hr(f"live: {name}")
        results, ledger, queue = [], Ledger(), []
        for d in docs:
            result = extract_with_retries(d, vendors, plan=plan, use_grounding=True)
            results.append(result)
            if result["status"] == "accepted":
                ledger.post(d["doc_id"], result["record"])
            else:
                ledger.park(d["doc_id"], result["last_record"])
                queue.append(review_item(result, d["source_text"]))
        m, bad = metrics(results), silent_corruptions(results, truth)
        summary[name] = {**m, "silent_corruptions": len(bad), "review_queue": [q["doc_id"] for q in queue]}
        print(f"accepted {m['accepted']}/{m['documents']}  retry rate {m['retry_rate']:.0%}  fallback rate {m['fallback_rate']:.0%}  "
              f"cost per accepted record ${m['cost_per_accepted'] or 0:.5f}  silent corruptions {len(bad)}")
        for q in queue:
            print(f"  review queue: {q['doc_id']} after {q['attempts']} attempt(s): {q['reason']}")
        print(f"  the next payment run would pay: {ledger.payable('INR')} INR (parked rows are excluded)")
    save("stage5.json", {"configs": summary})
