"""Plumbing for Lab 2.5 (build a tool and a loop). You do not edit this file.

It asks the same four library questions at every stage and prints ONE measured result per stage:

  stage 1  no tools: Claude can only guess what it cannot know          -> grounded answers
  stage 2  + your schema (TODO 1): Claude ASKS for a tool call, nothing runs -> right first request
  stage 3  + your dispatcher and loop (TODO 2, 3): the tool runs and the answer is grounded -> grounded answers
  stage 4  + your safe runner (TODO 4): errors and crashes become tool_results, and the loop always ends

The loop is a small state machine, as in Demo 2B: AWAITING_MODEL -> EXECUTING_TOOLS -> AWAITING_MODEL -> ... -> DONE.
"""
import json
import pathlib
from types import SimpleNamespace

from claude_client import MODEL_BALANCED, ask

HERE = pathlib.Path(__file__).parent
EVIDENCE = HERE / "evidence"
HOOKS = {"system": None, "tools": None, "answer": None, "run_tool_safely": None, "max_turns": 6}
STAGE_TITLES = {1: "no tools: Claude guesses", 2: "your schema: Claude asks for a tool", 3: "your loop: the tool runs",
                4: "your safe runner: errors never kill the loop"}

# label, question, tools Claude should ask for first, and the facts a grounded answer must contain (any one of each group)
QUESTIONS = [
    {"label": "needs find_book", "question": "Where is the book Dune and is a copy in?", "tools": {"find_book"}, "facts": [["SF-12"]]},
    {"label": "needs check_due_date", "question": "When is member M-200's book due back?", "tools": {"check_due_date"},
     "facts": [["2026-10-08", "October 8", "Oct 8", "8 October"]]},
    {"label": "needs both", "question": "Member M-100 asked when their loan is due and where I can find another copy of that title.",
     "tools": {"find_book", "check_due_date"}, "facts": [["2026-10-20", "October 20", "Oct 20", "20 October"], ["SF-12"]]},
    {"label": "needs none", "question": "What is the capital of France?", "tools": set(), "facts": [["Paris"]]},
]
ERROR_QUESTIONS = [
    {"label": "unknown book", "question": "Is the book Neuromancer in the library, and which shelf is it on?"},
    {"label": "member without a loan", "question": "When is member M-999's book due back?"},
]


def configure(**pieces):
    HOOKS.update(pieces)


def hr(title):
    print("\n" + "=" * 100 + f"\n{title}\n" + "=" * 100)


def grounded(text, facts):
    """True when the answer holds at least one spelling of every fact."""
    low = text.lower()
    return all(any(option.lower() in low for option in group) for group in facts)


def recorder():
    """Wrap ask() so we can see the loop's states and the messages it sent. Returns (send, log)."""
    log = {"states": [], "messages": []}

    def send(messages, **kwargs):
        log["messages"] = messages
        log["states"].append("AWAITING_MODEL")
        response = ask(messages, **kwargs)
        log["states"].append("EXECUTING_TOOLS" if response.stop_reason == "tool_use" else "DONE")
        return response
    return send, log


def flagged_errors(messages):
    """How many tool_result blocks in the conversation carried is_error=True."""
    blocks = [b for m in messages if m["role"] == "user" and isinstance(m["content"], list) for b in m["content"] if isinstance(b, dict)]
    return sum(1 for b in blocks if b.get("type") == "tool_result" and b.get("is_error") is True)


def save(name, data):
    EVIDENCE.mkdir(exist_ok=True)
    (EVIDENCE / name).write_text(json.dumps(data, indent=2, default=str), encoding="utf-8")


def history(stage):
    lines = []
    for n in range(1, stage + 1):
        path = EVIDENCE / f"stage{n}.json"
        if path.exists():
            lines.append(f"  stage {n}: {json.loads(path.read_text(encoding='utf-8'))['score']}")
    print("\nprogress so far:\n" + "\n".join(lines))


def short(text, n=110):
    text = " ".join(text.split())
    return text if len(text) <= n else text[:n] + "..."


# ---------------------------------------------------------------- stage 1: no tools
def stage1():
    rows = []
    for q in QUESTIONS:
        response = ask([{"role": "user", "content": q["question"]}], system=HOOKS["system"], model=MODEL_BALANCED, max_tokens=1024)
        text = "".join(b.text for b in response.content if b.type == "text")
        ok = grounded(text, q["facts"])
        rows.append({"label": q["label"], "answer": text, "grounded": ok, "tools_used": []})
        print(f"[{q['label']}] grounded: {'yes' if ok else 'no '}  answer: {short(text)}")
    right = sum(r["grounded"] for r in rows)
    score = f"{right}/{len(rows)} answers grounded (no tools)"
    print(f"\nRESULT: {score}. Claude cannot know a shelf code or a due date, so it guesses or says so.")
    return {"rows": rows, "score": score}


# ---------------------------------------------------------------- stage 2: one request, nothing runs
def stage2():
    tools = HOOKS["tools"]
    rows = []
    for q in QUESTIONS:
        response = ask([{"role": "user", "content": q["question"]}], system=HOOKS["system"], tools=tools, model=MODEL_BALANCED, max_tokens=1024)
        asked = [(b.name, dict(b.input)) for b in response.content if b.type == "tool_use"]
        names = {name for name, _ in asked}
        right = names <= q["tools"] and (bool(names) == bool(q["tools"]))
        rows.append({"label": q["label"], "stop_reason": response.stop_reason, "asked": [f"{n}({a})" for n, a in asked], "right": right})
        print(f"[{q['label']}] stop_reason: {response.stop_reason:<9} Claude asked for: {[f'{n}({a})' for n, a in asked] or 'nothing'}  right: {'yes' if right else 'no'}")
    right = sum(r["right"] for r in rows)
    score = f"{right}/{len(rows)} first requests right (nothing was executed)"
    print(f"\nRESULT: {score}. Claude only ASKED. Your program has not run any function yet.")
    return {"rows": rows, "score": score}


# ---------------------------------------------------------------- stage 3: the loop runs the tools
def stage3():
    rows = []
    for q in QUESTIONS:
        send, log = recorder()
        result = HOOKS["answer"](q["question"], send=send)
        ok = grounded(result["answer"], q["facts"])
        rows.append({"label": q["label"], "answer": result["answer"], "grounded": ok, "tools_used": result["tools_used"], "turns": result["turns"],
                     "gave_up": bool(result.get("gave_up")), "states": log["states"]})
        print(f"[{q['label']}] tools run: {result['tools_used'] or 'none'}  turns: {result['turns']}  grounded: {'yes' if ok else 'no '}  answer: {short(result['answer'], 80)}")
    both = next(r for r in rows if r["label"] == "needs both")
    print("\nstate trace of 'needs both':\n  " + " -> ".join(both["states"]))
    right = sum(r["grounded"] for r in rows)
    score = f"{right}/{len(rows)} answers grounded (tools run by your loop)"
    print(f"\nRESULT: {score}. In stage 1 only the France question was grounded.")
    return {"rows": rows, "score": score}


# ---------------------------------------------------------------- stage 4: errors, crashes and a loop that always ends
def endless_script():
    """A recorded bad model (no API call): it asks for a book that does not exist, again and again, and never answers."""
    count = {"n": 0}

    def send(messages, **kwargs):
        count["n"] += 1
        block = SimpleNamespace(type="tool_use", id=f"toolu_{count['n']}", name="find_book", input={"title": "Neuromancer"})
        return SimpleNamespace(content=[block], stop_reason="tool_use")
    return send


def stage4():
    print("PART 1 - live Claude, two questions whose tool call fails (the book and the loan do not exist):")
    live = []
    for q in ERROR_QUESTIONS:
        send, log = recorder()
        result = HOOKS["answer"](q["question"], send=send)
        flagged = flagged_errors(log["messages"])
        live.append({"label": q["label"], "answer": result["answer"], "tools_used": result["tools_used"], "flagged": flagged, "gave_up": bool(result.get("gave_up"))})
        print(f"[{q['label']}] tool errors flagged is_error: {flagged}  turns: {result['turns']}  answer: {short(result['answer'], 80)}")

    print("\nPART 2 - recorded, no model call: a tool that crashes on bad arguments:")
    try:
        content, is_error = HOOKS["run_tool_safely"]("find_book", {"wrong_argument": 1})
        crash_caught = is_error is True and "tool_crashed" in content
        print(f"  run_tool_safely returned is_error={is_error}: {short(content, 90)}")
    except Exception as exc:  # noqa: BLE001 - this is exactly the failure being shown
        content, crash_caught = f"CRASHED: {type(exc).__name__}: {exc}", False
        print(f"  the loop would have CRASHED here: {type(exc).__name__}: {exc}")

    print("\nPART 3 - recorded, no model call: a model that never stops asking for the missing book:")
    send = endless_script()
    result = HOOKS["answer"]("loop forever", send=send)
    print(f"  the loop stopped after {result['turns']} turns (limit {HOOKS['max_turns']}), gave_up={bool(result.get('gave_up'))}")

    flagged_total = sum(r["flagged"] for r in live)
    score = f"{flagged_total} live tool errors flagged, crash caught: {'yes' if crash_caught else 'NO'}, runaway loop stopped: {'yes' if result.get('gave_up') else 'NO'}"
    print(f"\nRESULT: {score}")
    return {"live": live, "crash_caught": crash_caught, "crash_content": content, "runaway": {"turns": result["turns"], "gave_up": bool(result.get("gave_up"))},
            "flagged_total": flagged_total, "score": score}


def run_stage(stage):
    if stage >= 2 and any(not t.get("name") for t in HOOKS["tools"]):
        raise SystemExit(f"TODO 1 is not done: CHECK_DUE_DATE_TOOL is still empty. Paste the snippet from the guide, then run stage {stage} again.")
    hr(f"STAGE {stage} - {STAGE_TITLES[stage]}")
    print(f"model: {MODEL_BALANCED}\n")
    data = {1: stage1, 2: stage2, 3: stage3, 4: stage4}[stage]()
    save(f"stage{stage}.json", {"stage": stage, **data})
    history(stage)
